/* ═══════════════════════════════════════════════════════════════════════
   Kids Learning Hub — app catalogue (source of truth for /apps/ pages)
   ═══════════════════════════════════════════════════════════════════════
   Every claim below was verified against the app source in
   ../../<app>_flutter/lib/ — lesson counts, topic lists and level counts
   are real. Do not add features here that the app does not ship.

   Consumed by tools/build-apps.js.
   ═══════════════════════════════════════════════════════════════════════ */
'use strict';

/* ── the six language apps are forks of one codebase, so their feature
      set is identical; only the taught language changes. ─────────────── */
function languageApp(o) {
  const T = o.target;                        // taught language, in 4 locales
  return {
    slug: o.slug, name: o.name, pkg: o.pkg, file: o.file,
    color: o.color, emoji: o.emoji, dl: o.dl, released: o.released,
    subject: T,
    tagline: {
      en: `Learn ${T.en} by playing`,
      fr: `Apprends ${o.leFr} en jouant`,
      es: `Aprende ${o.elEs} jugando`,
      ar: `تعلّم ${T.ar} باللعب`,
    },
    lede: {
      en: `${o.name} teaches ${T.en} to children aged 4–12 the way children actually learn a language: short illustrated lessons, a lot of listening, and games that make repetition feel like play. ${o.lessons} lessons, stories, songs and dialogues — all working offline, with no ads between exercises.`,
      fr: `${o.name} enseigne ${o.leFr} aux enfants de 4 à 12 ans comme on apprend vraiment une langue : de courtes leçons illustrées, beaucoup d'écoute, et des jeux qui transforment la répétition en plaisir. ${o.lessons} leçons, histoires, chansons et dialogues — le tout hors ligne, sans publicité entre les exercices.`,
      es: `${o.name} enseña ${o.elEs} a niños de 4 a 12 años como se aprende de verdad un idioma: lecciones breves ilustradas, mucha escucha y juegos que convierten la repetición en diversión. ${o.lessons} lecciones, cuentos, canciones y diálogos — todo sin conexión y sin anuncios entre ejercicios.`,
      ar: `يعلّم ${o.name} ${T.ar} للأطفال من 4 إلى 12 سنة بالطريقة التي يتعلّم بها الأطفال اللغة فعلًا: دروس قصيرة مصوّرة، واستماع كثير، وألعاب تجعل التكرار متعة. ${o.lessons} درسًا وقصصًا وأغاني وحوارات — كلّها تعمل دون إنترنت، وبلا إعلانات بين التمارين.`,
    },
    stats: [
      { v: String(o.lessons), l: { en: 'Lessons', fr: 'Leçons', es: 'Lecciones', ar: 'درسًا' } },
      { v: '4–12', l: { en: 'Ages', fr: 'Âges', es: 'Edades', ar: 'الأعمار' } },
      { v: '100%', l: { en: 'Offline', fr: 'Hors ligne', es: 'Sin conexión', ar: 'دون إنترنت' } },
      { v: '0 €', l: { en: 'To download', fr: 'Au téléchargement', es: 'Al descargar', ar: 'للتحميل' } },
    ],
    features: [
      { i: '📚',
        t: { en: `${o.lessons} illustrated lessons`, fr: `${o.lessons} leçons illustrées`, es: `${o.lessons} lecciones ilustradas`, ar: `${o.lessons} درسًا مصوّرًا` },
        d: { en: `Vocabulary grouped by theme — colours, animals, family, food, school, body, time — each word illustrated and read aloud.`,
             fr: `Du vocabulaire par thème — couleurs, animaux, famille, nourriture, école, corps, temps — chaque mot illustré et lu à voix haute.`,
             es: `Vocabulario por temas — colores, animales, familia, comida, escuela, cuerpo, tiempo — cada palabra ilustrada y leída en voz alta.`,
             ar: `مفردات مرتّبة حسب الموضوع — الألوان والحيوانات والعائلة والطعام والمدرسة والجسم والوقت — كل كلمة مصوّرة ومنطوقة.` } },
      { i: '✍️',
        t: { en: 'Guided tracing', fr: 'Tracé guidé', es: 'Trazado guiado', ar: 'تتبّع موجّه' },
        d: { en: `Children trace ${T.en} letters and words with a finger, following animated strokes in the right order.`,
             fr: `L'enfant trace les lettres et les mots ${o.adjFr} au doigt, en suivant des tracés animés dans le bon ordre.`,
             es: `El niño traza letras y palabras ${o.adjEs} con el dedo, siguiendo trazos animados en el orden correcto.`,
             ar: `يتتبّع الطفل حروف ${T.ar} وكلماتها بإصبعه، متّبعًا حركات متحرّكة بالترتيب الصحيح.` } },
      { i: '🎧',
        t: { en: 'Listening & pronunciation', fr: 'Écoute et prononciation', es: 'Escucha y pronunciación', ar: 'استماع ونطق' },
        d: { en: 'Every word is spoken. Listen-and-pick exercises train the ear before the child is asked to produce anything.',
             fr: 'Chaque mot est prononcé. Des exercices d\'écoute entraînent l\'oreille avant de demander à l\'enfant de produire.',
             es: 'Cada palabra se pronuncia. Los ejercicios de escucha entrenan el oído antes de pedirle nada al niño.',
             ar: 'كل كلمة منطوقة. تمارين الاستماع والاختيار تدرّب الأذن قبل أن يُطلب من الطفل إنتاج أي شيء.' } },
      { i: '📖',
        t: { en: 'Stories, songs & dialogues', fr: 'Histoires, chansons et dialogues', es: 'Cuentos, canciones y diálogos', ar: 'قصص وأغانٍ وحوارات' },
        d: { en: 'Illustrated stories, sing-along songs and everyday dialogues put the vocabulary back into real sentences.',
             fr: 'Des histoires illustrées, des chansons à chanter et des dialogues du quotidien remettent le vocabulaire dans de vraies phrases.',
             es: 'Cuentos ilustrados, canciones para cantar y diálogos cotidianos devuelven el vocabulario a frases reales.',
             ar: 'قصص مصوّرة وأغانٍ للترديد وحوارات يومية تعيد المفردات إلى جمل حقيقية.' } },
      { i: '🎮',
        t: { en: 'Eight ways to practise', fr: 'Huit façons de réviser', es: 'Ocho formas de practicar', ar: 'ثماني طرق للمراجعة' },
        d: { en: 'Flashcards, memory pairs, matching, hangman, spelling, quiz, sentence builder and listen-and-pick — the same words, never the same drill.',
             fr: 'Cartes, paires de mémoire, association, pendu, orthographe, quiz, constructeur de phrases et écoute — les mêmes mots, jamais le même exercice.',
             es: 'Tarjetas, parejas de memoria, asociación, ahorcado, ortografía, quiz, constructor de frases y escucha — las mismas palabras, nunca el mismo ejercicio.',
             ar: 'بطاقات وذاكرة وتوصيل ومشنقة وإملاء واختبار وبناء الجمل واستماع — الكلمات نفسها، دون تكرار التمرين نفسه.' } },
      { i: '📈',
        t: { en: 'Review that targets mistakes', fr: 'Une révision ciblée sur les erreurs', es: 'Repaso centrado en los errores', ar: 'مراجعة تستهدف الأخطاء' },
        d: { en: 'Missed words come back on a spaced schedule, and a parents section shows what has been learned — with badges and printable certificates for the child.',
             fr: 'Les mots ratés reviennent à intervalles espacés, et un espace parents montre ce qui est acquis — avec badges et certificats imprimables pour l\'enfant.',
             es: 'Las palabras falladas vuelven de forma espaciada, y una sección para padres muestra lo aprendido — con insignias y certificados imprimibles.',
             ar: 'الكلمات الخاطئة تعود وفق جدول متباعد، وقسم لأولياء الأمور يعرض ما تعلّمه الطفل — مع أوسمة وشهادات قابلة للطباعة.' } },
    ],
    faq: {
      en: [
        [`What age is ${o.name} for?`, `It is designed for children aged 4 to 12. Pre-readers can use the picture and listening exercises on their own, because every word is spoken aloud; older children move on to spelling, sentence building and the dialogues.`],
        [`Does ${o.name} work without internet?`, `Yes. All ${o.lessons} lessons, the audio, the stories and the games are stored in the app, so it works on a plane, in the car or on a tablet with no SIM card.`],
        [`Is ${o.name} really free?`, `The app is free to download and a large part of the content is free to use. An optional paid unlock removes the ads and opens the remaining lessons — nothing is charged automatically.`],
        [`Is it safe for young children?`, `Yes. There is no chat, no user accounts and no personalised advertising. Anything that leaves the app — links, purchases, external pages — sits behind a parental gate that a young child cannot pass.`],
      ],
      fr: [
        [`À quel âge s'adresse ${o.name} ?`, `L'application est conçue pour les enfants de 4 à 12 ans. Les non-lecteurs peuvent utiliser seuls les exercices d'images et d'écoute, car chaque mot est prononcé ; les plus grands passent à l'orthographe, à la construction de phrases et aux dialogues.`],
        [`${o.name} fonctionne-t-il sans internet ?`, `Oui. Les ${o.lessons} leçons, l'audio, les histoires et les jeux sont stockés dans l'application : elle fonctionne en avion, en voiture ou sur une tablette sans carte SIM.`],
        [`${o.name} est-il vraiment gratuit ?`, `L'application est gratuite au téléchargement et une grande partie du contenu est libre d'accès. Un déblocage payant facultatif retire les publicités et ouvre les leçons restantes — rien n'est prélevé automatiquement.`],
        [`Est-ce sûr pour les jeunes enfants ?`, `Oui. Pas de chat, pas de compte utilisateur, pas de publicité personnalisée. Tout ce qui sort de l'application — liens, achats, pages externes — est protégé par un contrôle parental qu'un jeune enfant ne peut pas franchir.`],
      ],
      es: [
        [`¿Para qué edad es ${o.name}?`, `Está pensada para niños de 4 a 12 años. Los que aún no leen pueden usar solos los ejercicios de imágenes y escucha, porque cada palabra se pronuncia; los mayores pasan a la ortografía, la construcción de frases y los diálogos.`],
        [`¿${o.name} funciona sin internet?`, `Sí. Las ${o.lessons} lecciones, el audio, los cuentos y los juegos están dentro de la app, así que funciona en un avión, en el coche o en una tableta sin SIM.`],
        [`¿${o.name} es realmente gratis?`, `La app es gratuita y buena parte del contenido es de acceso libre. Un desbloqueo de pago opcional quita los anuncios y abre las lecciones restantes — no se cobra nada automáticamente.`],
        [`¿Es segura para niños pequeños?`, `Sí. No hay chat, ni cuentas de usuario, ni publicidad personalizada. Todo lo que sale de la app — enlaces, compras, páginas externas — está detrás de un control parental que un niño pequeño no puede pasar.`],
      ],
      ar: [
        [`ما العمر المناسب لتطبيق ${o.name}؟`, `صُمّم للأطفال من 4 إلى 12 سنة. من لا يقرأ بعد يستطيع استخدام تمارين الصور والاستماع وحده لأن كل كلمة منطوقة، والأكبر ينتقلون إلى الإملاء وبناء الجمل والحوارات.`],
        [`هل يعمل ${o.name} دون إنترنت؟`, `نعم. الدروس الـ${o.lessons} والصوت والقصص والألعاب كلّها مخزّنة داخل التطبيق، فيعمل في الطائرة أو السيارة أو على لوحٍ بلا شريحة.`],
        [`هل ${o.name} مجاني فعلًا؟`, `التطبيق مجاني التحميل وجزء كبير من المحتوى متاح مجانًا. وهناك فتحٌ مدفوع اختياري يزيل الإعلانات ويفتح بقية الدروس — دون أي خصم تلقائي.`],
        [`هل هو آمن للأطفال الصغار؟`, `نعم. لا دردشة ولا حسابات ولا إعلانات مخصّصة. وكل ما يخرج من التطبيق — روابط أو شراء أو صفحات خارجية — محميّ ببوابة أبوية لا يجتازها طفل صغير.`],
      ],
    },
  };
}

/* ── catalogue (same order as the homepage) ───────────────────────────── */
module.exports = [

  /* ── 1 · MathoKids ─────────────────────────────────────────────────── */
  {
    slug: 'mathokids', name: 'MathoKids', pkg: 'com.matho.primaire',
    file: 'mathokids.png', color: '#3B82F6', emoji: '🔢', dl: '50K+', released: '2026-01-15',
    subject: { en: 'Maths', fr: 'Maths', es: 'Matemáticas', ar: 'الرياضيات' },
    tagline: { en: 'Learn primary maths by playing', fr: 'Apprends les maths en jouant',
               es: 'Aprende matemáticas jugando', ar: 'تعلّم الرياضيات باللعب' },
    lede: {
      en: 'MathoKids covers the whole primary maths programme — numbers, the four operations, times tables, mental arithmetic and word problems — as short exercises with instant feedback. Built by a mathematics teacher, it works entirely offline and keeps a record of every mistake so the child can come back to it.',
      fr: "MathoKids couvre tout le programme de maths du primaire — nombres, quatre opérations, tables, calcul mental et problèmes — sous forme d'exercices courts avec correction immédiate. Conçue par un professeur de mathématiques, l'appli fonctionne entièrement hors ligne et garde la trace de chaque erreur pour y revenir.",
      es: 'MathoKids cubre todo el programa de matemáticas de primaria — números, las cuatro operaciones, tablas, cálculo mental y problemas — en ejercicios cortos con corrección inmediata. Creada por un profesor de matemáticas, funciona sin conexión y guarda cada error para volver a él.',
      ar: 'يغطّي MathoKids برنامج الرياضيات الابتدائي كاملًا — الأعداد والعمليات الأربع وجداول الضرب والحساب الذهني والمسائل — في تمارين قصيرة بتصحيح فوري. صمّمه أستاذ رياضيات، ويعمل دون إنترنت تمامًا، ويحتفظ بكل خطأ ليعود إليه الطفل.',
    },
    stats: [
      { v: '28', l: { en: 'Calculation rules', fr: 'Règles de calcul', es: 'Reglas de cálculo', ar: 'قاعدة حسابية' } },
      { v: '48', l: { en: 'Word problems', fr: 'Problèmes', es: 'Problemas', ar: 'مسألة' } },
      { v: '6–12', l: { en: 'Ages', fr: 'Âges', es: 'Edades', ar: 'الأعمار' } },
      { v: '100%', l: { en: 'Offline', fr: 'Hors ligne', es: 'Sin conexión', ar: 'دون إنترنت' } },
    ],
    features: [
      { i: '➗', t: { en: 'The whole primary programme', fr: 'Tout le programme du primaire', es: 'Todo el programa de primaria', ar: 'البرنامج الابتدائي كاملًا' },
        d: { en: 'Numbers, addition, subtraction, multiplication, division, fractions and geometry — organised in modules that follow the school year.',
             fr: 'Nombres, addition, soustraction, multiplication, division, fractions et géométrie — en modules qui suivent l\'année scolaire.',
             es: 'Números, suma, resta, multiplicación, división, fracciones y geometría — en módulos que siguen el curso escolar.',
             ar: 'الأعداد والجمع والطرح والضرب والقسمة والكسور والهندسة — في وحدات تتبع السنة الدراسية.' } },
      { i: '⚡', t: { en: 'Mental maths & times tables', fr: 'Calcul mental et tables', es: 'Cálculo mental y tablas', ar: 'حساب ذهني وجداول' },
        d: { en: 'A dedicated mental-arithmetic trainer and a times-table module that builds speed a few minutes at a time.',
             fr: 'Un entraîneur de calcul mental et un module de tables qui construisent la rapidité quelques minutes à la fois.',
             es: 'Un entrenador de cálculo mental y un módulo de tablas que gana velocidad en pocos minutos al día.',
             ar: 'مدرّب للحساب الذهني ووحدة لجداول الضرب تبنيان السرعة في دقائق قليلة يوميًا.' } },
      { i: '📝', t: { en: '48 word problems', fr: '48 problèmes', es: '48 problemas', ar: '48 مسألة' },
        d: { en: 'Real-life problems that teach children to read a question, find what matters and choose the operation themselves.',
             fr: 'Des problèmes concrets qui apprennent à lire l\'énoncé, repérer l\'essentiel et choisir soi-même l\'opération.',
             es: 'Problemas de la vida real que enseñan a leer el enunciado, ver lo importante y elegir la operación.',
             ar: 'مسائل من الحياة اليومية تعلّم الطفل قراءة السؤال وتمييز المهم واختيار العملية بنفسه.' } },
      { i: '🎯', t: { en: 'Mistakes become practice', fr: 'Les erreurs deviennent des exercices', es: 'Los errores se convierten en práctica', ar: 'الأخطاء تتحوّل إلى تمرين' },
        d: { en: 'Every wrong answer is stored and comes back on a spaced-review schedule, with the calculation rule explained again.',
             fr: 'Chaque erreur est enregistrée et revient en révision espacée, avec la règle de calcul réexpliquée.',
             es: 'Cada error se guarda y vuelve en repaso espaciado, con la regla de cálculo explicada de nuevo.',
             ar: 'كل إجابة خاطئة تُحفظ وتعود في مراجعة متباعدة، مع إعادة شرح القاعدة الحسابية.' } },
      { i: '⚔️', t: { en: 'Duels and missions', fr: 'Duels et missions', es: 'Duelos y misiones', ar: 'مبارزات ومهامّ' },
        d: { en: 'Maths duel, co-op room and rescue missions turn revision into a game two children can play side by side.',
             fr: 'Duel de maths, salle coopérative et missions de sauvetage transforment la révision en jeu à deux.',
             es: 'Duelo de matemáticas, sala cooperativa y misiones de rescate convierten el repaso en un juego para dos.',
             ar: 'مبارزة رياضيات وغرفة تعاونية ومهامّ إنقاذ تحوّل المراجعة إلى لعبة يلعبها طفلان معًا.' } },
      { i: '👨‍👩‍👧', t: { en: 'Profiles & parent dashboard', fr: 'Profils et espace parents', es: 'Perfiles y panel de padres', ar: 'ملفات ولوحة أولياء' },
        d: { en: 'Several children can share one device, each with their own progress, badges, statistics and printable certificates.',
             fr: 'Plusieurs enfants partagent un appareil, chacun avec sa progression, ses badges, ses statistiques et ses certificats.',
             es: 'Varios niños comparten un dispositivo, cada uno con su progreso, insignias, estadísticas y certificados.',
             ar: 'يتشارك عدّة أطفال جهازًا واحدًا، لكل واحد تقدّمه وأوسمته وإحصاءاته وشهاداته.' } },
    ],
    faq: {
      en: [
        ['What age is MathoKids for?', 'It follows the primary-school maths programme, so it suits children roughly 6 to 12. Younger children can start with the numbers and counting modules, which need no reading.'],
        ['Does MathoKids work offline?', 'Yes, completely. Lessons, exercises, word problems and games are all stored in the app — no connection is needed at any point.'],
        ['Who made MathoKids?', 'It is built by Ayyoub EL HAJJI, a mathematics teacher from Morocco. The exercise order, the calculation rules and the mistake-review system come from classroom experience, not from a generic template.'],
        ['Is MathoKids free?', 'Yes, it is free to download and the core content is free to use. An optional paid unlock removes ads and opens the remaining modules.'],
      ],
      fr: [
        ['À quel âge s\'adresse MathoKids ?', 'L\'appli suit le programme de maths du primaire : elle convient environ de 6 à 12 ans. Les plus jeunes peuvent commencer par les modules de nombres et de comptage, qui ne demandent pas de lecture.'],
        ['MathoKids fonctionne-t-il hors ligne ?', 'Oui, totalement. Leçons, exercices, problèmes et jeux sont stockés dans l\'application — aucune connexion n\'est nécessaire.'],
        ['Qui a créé MathoKids ?', 'L\'application est développée par Ayyoub EL HAJJI, professeur de mathématiques au Maroc. La progression des exercices, les règles de calcul et le système de révision des erreurs viennent de la classe, pas d\'un modèle générique.'],
        ['MathoKids est-il gratuit ?', 'Oui, le téléchargement et le contenu principal sont gratuits. Un déblocage payant facultatif retire les publicités et ouvre les modules restants.'],
      ],
      es: [
        ['¿Para qué edad es MathoKids?', 'Sigue el programa de matemáticas de primaria, así que va bien de 6 a 12 años. Los más pequeños pueden empezar por los módulos de números y conteo, que no requieren leer.'],
        ['¿MathoKids funciona sin conexión?', 'Sí, totalmente. Lecciones, ejercicios, problemas y juegos están dentro de la app — no hace falta conexión en ningún momento.'],
        ['¿Quién hizo MathoKids?', 'La creó Ayyoub EL HAJJI, profesor de matemáticas de Marruecos. El orden de los ejercicios, las reglas de cálculo y el repaso de errores vienen del aula, no de una plantilla genérica.'],
        ['¿MathoKids es gratis?', 'Sí, la descarga y el contenido principal son gratis. Un desbloqueo de pago opcional quita los anuncios y abre los módulos restantes.'],
      ],
      ar: [
        ['ما العمر المناسب لتطبيق MathoKids؟', 'يتبع برنامج الرياضيات الابتدائي، فيناسب تقريبًا من 6 إلى 12 سنة. ويمكن للأصغر البدء بوحدات الأعداد والعدّ التي لا تتطلّب قراءة.'],
        ['هل يعمل MathoKids دون إنترنت؟', 'نعم، تمامًا. الدروس والتمارين والمسائل والألعاب كلّها داخل التطبيق — ولا حاجة إلى اتصال في أي لحظة.'],
        ['من صنع MathoKids؟', 'طوّره أيوب الحاجي، أستاذ رياضيات من المغرب. ترتيب التمارين وقواعد الحساب ونظام مراجعة الأخطاء كلّها من تجربة القسم، لا من قالب جاهز.'],
        ['هل MathoKids مجاني؟', 'نعم، التحميل والمحتوى الأساسي مجانيان. وهناك فتح مدفوع اختياري يزيل الإعلانات ويفتح بقية الوحدات.'],
      ],
    },
  },

  /* ── 2 · ScienKids ─────────────────────────────────────────────────── */
  {
    slug: 'scienkids', name: 'ScienKids', pkg: 'com.vsmedia.scienkids',
    file: 'scienkids.png', color: '#15A34A', emoji: '🔬', dl: 'New', released: '2026-07-01',
    subject: { en: 'Science', fr: 'Sciences', es: 'Ciencias', ar: 'العلوم' },
    tagline: { en: 'Learn science by playing', fr: 'Apprends les sciences en jouant',
               es: 'Aprende ciencias jugando', ar: 'تعلّم العلوم باللعب' },
    lede: {
      en: 'ScienKids answers the questions children actually ask — why is the sky blue, where does rain come from, how does my body work. Ten science topics, each with illustrated lessons, seven kinds of game, safe experiments to try at home and colouring pages. Entirely offline.',
      fr: "ScienKids répond aux questions que les enfants posent vraiment — pourquoi le ciel est bleu, d'où vient la pluie, comment fonctionne mon corps. Dix sujets scientifiques, chacun avec des leçons illustrées, sept types de jeux, des expériences sûres à faire à la maison et des coloriages. Entièrement hors ligne.",
      es: 'ScienKids responde a las preguntas que los niños hacen de verdad — por qué el cielo es azul, de dónde viene la lluvia, cómo funciona mi cuerpo. Diez temas de ciencia, cada uno con lecciones ilustradas, siete tipos de juego, experimentos seguros para casa y páginas para colorear. Sin conexión.',
      ar: 'يجيب ScienKids عن الأسئلة التي يطرحها الأطفال فعلًا — لماذا السماء زرقاء، من أين يأتي المطر، كيف يعمل جسمي. عشرة مواضيع علمية، لكل منها دروس مصوّرة وسبعة أنواع من الألعاب وتجارب آمنة تُجرى في البيت وصفحات تلوين. ويعمل دون إنترنت تمامًا.',
    },
    stats: [
      { v: '10', l: { en: 'Science topics', fr: 'Sujets', es: 'Temas', ar: 'موضوعًا' } },
      { v: '7', l: { en: 'Game types', fr: 'Types de jeux', es: 'Tipos de juego', ar: 'أنواع ألعاب' } },
      { v: '4–12', l: { en: 'Ages', fr: 'Âges', es: 'Edades', ar: 'الأعمار' } },
      { v: '100%', l: { en: 'Offline', fr: 'Hors ligne', es: 'Sin conexión', ar: 'دون إنترنت' } },
    ],
    features: [
      { i: '🪐', t: { en: 'Ten topics to explore', fr: 'Dix sujets à explorer', es: 'Diez temas para explorar', ar: 'عشرة مواضيع للاستكشاف' },
        d: { en: 'Space, animals, plants, water, physics, chemistry, the Earth, the human body, the five senses and dinosaurs.',
             fr: "L'espace, les animaux, les plantes, l'eau, la physique, la chimie, la Terre, le corps humain, les cinq sens et les dinosaures.",
             es: 'El espacio, los animales, las plantas, el agua, la física, la química, la Tierra, el cuerpo humano, los cinco sentidos y los dinosaurios.',
             ar: 'الفضاء والحيوانات والنباتات والماء والفيزياء والكيمياء والأرض وجسم الإنسان والحواس الخمس والديناصورات.' } },
      { i: '🧪', t: { en: 'Experiments to do at home', fr: 'Des expériences à faire à la maison', es: 'Experimentos para hacer en casa', ar: 'تجارب تُجرى في البيت' },
        d: { en: 'Step-by-step experiments using kitchen materials, each ending with the explanation of why it happened.',
             fr: "Des expériences pas à pas avec du matériel de cuisine, chacune se terminant par l'explication du pourquoi.",
             es: 'Experimentos paso a paso con material de cocina, cada uno con la explicación de por qué ocurre.',
             ar: 'تجارب خطوة بخطوة بأدوات المطبخ، تنتهي كل واحدة بتفسير سبب ما حدث.' } },
      { i: '🎮', t: { en: 'Seven kinds of game', fr: 'Sept types de jeux', es: 'Siete tipos de juego', ar: 'سبعة أنواع من الألعاب' },
        d: { en: 'Quiz, true-or-false, memory, matching, drag-and-drop, odd-one-out and puzzles — so the same topic is revised seven different ways.',
             fr: 'Quiz, vrai ou faux, mémoire, association, glisser-déposer, intrus et puzzles — un même sujet révisé de sept façons.',
             es: 'Quiz, verdadero o falso, memoria, asociación, arrastrar y soltar, intruso y puzles — un mismo tema repasado de siete formas.',
             ar: 'اختبار وصح/خطأ وذاكرة وتوصيل وسحب وإفلات واستبعاد الدخيل وأحاجٍ — الموضوع نفسه يُراجَع بسبع طرق.' } },
      { i: '🎨', t: { en: 'Colouring pages', fr: 'Pages de coloriage', es: 'Páginas para colorear', ar: 'صفحات تلوين' },
        d: { en: 'A quiet activity between lessons — colour the planets, the animals, the parts of a plant.',
             fr: 'Une activité calme entre deux leçons — colorier les planètes, les animaux, les parties d\'une plante.',
             es: 'Una actividad tranquila entre lecciones — colorear los planetas, los animales, las partes de una planta.',
             ar: 'نشاط هادئ بين الدروس — تلوين الكواكب والحيوانات وأجزاء النبتة.' } },
      { i: '👩‍🔬', t: { en: 'Meet the scientists', fr: 'Rencontre les scientifiques', es: 'Conoce a los científicos', ar: 'تعرّف على العلماء' },
        d: { en: 'Short portraits of the people behind the discoveries, so science has faces and stories, not only facts.',
             fr: 'De courts portraits de ceux qui ont fait les découvertes : la science a des visages et des histoires, pas seulement des faits.',
             es: 'Retratos breves de quienes hicieron los descubrimientos: la ciencia tiene caras e historias, no solo datos.',
             ar: 'صور مختصرة لمن قاموا بالاكتشافات، فللعلم وجوه وحكايات لا معلومات فقط.' } },
      { i: '🔒', t: { en: 'Safe by design', fr: 'Sûr par conception', es: 'Seguro por diseño', ar: 'آمن بالتصميم' },
        d: { en: 'No chat, no accounts, no personalised ads, and a parental gate in front of anything that leaves the app.',
             fr: 'Pas de chat, pas de compte, pas de publicité personnalisée, et un contrôle parental devant tout ce qui sort de l\'appli.',
             es: 'Sin chat, sin cuentas, sin anuncios personalizados, y un control parental ante todo lo que sale de la app.',
             ar: 'لا دردشة ولا حسابات ولا إعلانات مخصّصة، وبوابة أبوية أمام كل ما يخرج من التطبيق.' } },
    ],
    faq: {
      en: [
        ['What age is ScienKids for?', 'Children from about 4 to 12. Younger children use the pictures, the colouring and the simpler games; older ones read the lessons and try the experiments.'],
        ['What science topics are covered?', 'Ten: space, animals, plants, water, physics, chemistry, the Earth, the human body, the senses and dinosaurs — each with its own lessons, games and facts.'],
        ['Are the experiments safe?', 'They use ordinary household and kitchen materials and are written for children, but an adult should always be present — as the app itself reminds you.'],
        ['Does it need an internet connection?', 'No. Every lesson, game, experiment and colouring page is stored in the app and works offline.'],
      ],
      fr: [
        ['À quel âge s\'adresse ScienKids ?', 'Aux enfants d\'environ 4 à 12 ans. Les plus jeunes utilisent les images, les coloriages et les jeux simples ; les plus grands lisent les leçons et font les expériences.'],
        ['Quels sujets scientifiques sont couverts ?', 'Dix : l\'espace, les animaux, les plantes, l\'eau, la physique, la chimie, la Terre, le corps humain, les sens et les dinosaures — chacun avec ses leçons, ses jeux et ses anecdotes.'],
        ['Les expériences sont-elles sans danger ?', 'Elles utilisent du matériel courant de la maison et sont écrites pour des enfants, mais un adulte doit toujours être présent — l\'application le rappelle elle-même.'],
        ['Faut-il une connexion internet ?', 'Non. Chaque leçon, jeu, expérience et coloriage est stocké dans l\'application et fonctionne hors ligne.'],
      ],
      es: [
        ['¿Para qué edad es ScienKids?', 'Para niños de unos 4 a 12 años. Los más pequeños usan las imágenes, los dibujos para colorear y los juegos sencillos; los mayores leen las lecciones y hacen los experimentos.'],
        ['¿Qué temas de ciencia incluye?', 'Diez: el espacio, los animales, las plantas, el agua, la física, la química, la Tierra, el cuerpo humano, los sentidos y los dinosaurios — cada uno con sus lecciones, juegos y curiosidades.'],
        ['¿Los experimentos son seguros?', 'Usan materiales corrientes de casa y están escritos para niños, pero siempre debe haber un adulto presente — la propia app lo recuerda.'],
        ['¿Necesita conexión a internet?', 'No. Cada lección, juego, experimento y página para colorear está en la app y funciona sin conexión.'],
      ],
      ar: [
        ['ما العمر المناسب لتطبيق ScienKids؟', 'للأطفال من نحو 4 إلى 12 سنة. الأصغر يستعملون الصور والتلوين والألعاب البسيطة، والأكبر يقرؤون الدروس ويجرّبون التجارب.'],
        ['ما المواضيع العلمية التي يغطّيها؟', 'عشرة: الفضاء والحيوانات والنباتات والماء والفيزياء والكيمياء والأرض وجسم الإنسان والحواس والديناصورات — لكل منها دروسه وألعابه وطرائفه.'],
        ['هل التجارب آمنة؟', 'تستعمل موادّ منزلية عادية ومكتوبة للأطفال، لكن يجب أن يحضر شخص بالغ دائمًا — والتطبيق نفسه ينبّه إلى ذلك.'],
        ['هل يحتاج إلى اتصال بالإنترنت؟', 'لا. كل درس ولعبة وتجربة وصفحة تلوين مخزّنة داخل التطبيق وتعمل دون إنترنت.'],
      ],
    },
  },

  /* ── 3 · CodoKids ──────────────────────────────────────────────────── */
  {
    slug: 'codokids', name: 'CodoKids', pkg: 'com.vsmedia.codokids',
    file: 'codokids.png', color: '#5D4037', emoji: '🤖', dl: 'New', released: '2026-07-05',
    subject: { en: 'Coding', fr: 'Codage', es: 'Programación', ar: 'البرمجة' },
    tagline: { en: 'Learn coding by playing', fr: 'Apprends le codage en jouant',
               es: 'Aprende a programar jugando', ar: 'تعلّم البرمجة باللعب' },
    lede: {
      en: 'CodoKids teaches computational thinking before syntax. Children program a robot through 40 hand-tested maze levels — sequences, then loops, then debugging — and explore nine topics that explain what a computer, an algorithm or the internet actually is. No typing required, and no connection either.',
      fr: "CodoKids enseigne la pensée informatique avant la syntaxe. L'enfant programme un robot à travers 40 niveaux de labyrinthe testés un à un — séquences, puis boucles, puis débogage — et explore neuf sujets qui expliquent ce qu'est vraiment un ordinateur, un algorithme ou internet. Sans clavier, et sans connexion.",
      es: 'CodoKids enseña pensamiento computacional antes que sintaxis. El niño programa un robot por 40 niveles de laberinto probados uno a uno — secuencias, luego bucles, luego depuración — y explora nueve temas que explican qué es de verdad un ordenador, un algoritmo o internet. Sin teclado y sin conexión.',
      ar: 'يعلّم CodoKids التفكير الحاسوبي قبل قواعد الكتابة. يبرمج الطفل روبوتًا عبر 40 مستوى متاهة مختبَرة واحدًا واحدًا — تسلسلات ثم حلقات ثم تصحيح أخطاء — ويستكشف تسعة مواضيع تشرح ما الحاسوب والخوارزمية والإنترنت حقًّا. دون كتابة ودون إنترنت.',
    },
    stats: [
      { v: '40', l: { en: 'CodeQuest levels', fr: 'Niveaux CodeQuest', es: 'Niveles CodeQuest', ar: 'مستوى CodeQuest' } },
      { v: '9', l: { en: 'Topics', fr: 'Sujets', es: 'Temas', ar: 'مواضيع' } },
      { v: '4–13', l: { en: 'Ages', fr: 'Âges', es: 'Edades', ar: 'الأعمار' } },
      { v: '100%', l: { en: 'Offline', fr: 'Hors ligne', es: 'Sin conexión', ar: 'دون إنترنت' } },
    ],
    features: [
      { i: '🤖', t: { en: 'CodeQuest — 40 robot levels', fr: 'CodeQuest — 40 niveaux', es: 'CodeQuest — 40 niveles', ar: 'CodeQuest — 40 مستوى' },
        d: { en: 'Drag instruction blocks to guide a robot through a maze. Difficulty rises from three steps to loops and nested logic — every level tested to be solvable.',
             fr: 'Glisse des blocs d\'instructions pour guider un robot dans un labyrinthe. La difficulté passe de trois pas aux boucles et à la logique imbriquée — chaque niveau testé comme résoluble.',
             es: 'Arrastra bloques de instrucciones para guiar a un robot por un laberinto. La dificultad va de tres pasos a bucles y lógica anidada — cada nivel probado y resoluble.',
             ar: 'اسحب مكعّبات الأوامر لتقود روبوتًا في متاهة. تتدرّج الصعوبة من ثلاث خطوات إلى الحلقات والمنطق المتداخل — وكل مستوى مختبَر وقابل للحلّ.' } },
      { i: '💡', t: { en: 'Nine topics to understand', fr: 'Neuf sujets à comprendre', es: 'Nueve temas para entender', ar: 'تسعة مواضيع للفهم' },
        d: { en: 'Computers, algorithms, loops, bugs, the internet, data, robots, games and secret codes — explained without jargon.',
             fr: 'Ordinateurs, algorithmes, boucles, bugs, internet, données, robots, jeux et codes secrets — expliqués sans jargon.',
             es: 'Ordenadores, algoritmos, bucles, errores, internet, datos, robots, juegos y códigos secretos — explicados sin jerga.',
             ar: 'الحواسيب والخوارزميات والحلقات والأخطاء البرمجية والإنترنت والبيانات والروبوتات والألعاب والشيفرات السرّية — بشرح بلا مصطلحات معقّدة.' } },
      { i: '🐞', t: { en: 'Debugging as a skill', fr: 'Le débogage comme compétence', es: 'Depurar como habilidad', ar: 'تصحيح الأخطاء مهارة' },
        d: { en: 'A whole topic on bugs: children learn that a program failing is normal, and that finding why is the actual job.',
             fr: 'Un sujet entier sur les bugs : l\'enfant apprend qu\'un programme qui échoue est normal, et que trouver pourquoi est le vrai travail.',
             es: 'Un tema entero sobre errores: el niño aprende que un programa que falla es normal, y que encontrar el porqué es el trabajo real.',
             ar: 'موضوع كامل عن الأخطاء البرمجية: يتعلّم الطفل أن فشل البرنامج أمر طبيعي، وأن اكتشاف السبب هو العمل الحقيقي.' } },
      { i: '🎮', t: { en: 'Seven kinds of game', fr: 'Sept types de jeux', es: 'Siete tipos de juego', ar: 'سبعة أنواع من الألعاب' },
        d: { en: 'Quiz, true-or-false, memory, matching, drag-and-drop, odd-one-out and puzzles reinforce each topic.',
             fr: 'Quiz, vrai ou faux, mémoire, association, glisser-déposer, intrus et puzzles renforcent chaque sujet.',
             es: 'Quiz, verdadero o falso, memoria, asociación, arrastrar y soltar, intruso y puzles refuerzan cada tema.',
             ar: 'اختبار وصح/خطأ وذاكرة وتوصيل وسحب وإفلات واستبعاد الدخيل وأحاجٍ تعزّز كل موضوع.' } },
      { i: '⌨️', t: { en: 'No reading or typing needed', fr: 'Ni lecture ni clavier', es: 'Sin leer ni teclear', ar: 'دون قراءة أو كتابة' },
        d: { en: 'Instructions are icons, not words, so a four-year-old can start CodeQuest before learning to read.',
             fr: 'Les instructions sont des icônes, pas des mots : un enfant de quatre ans peut commencer CodeQuest avant de savoir lire.',
             es: 'Las instrucciones son iconos, no palabras: un niño de cuatro años puede empezar CodeQuest antes de saber leer.',
             ar: 'الأوامر أيقونات لا كلمات، فيستطيع ابن الأربع سنوات بدء CodeQuest قبل أن يتعلّم القراءة.' } },
      { i: '🧑‍💻', t: { en: 'The pioneers of computing', fr: 'Les pionniers de l\'informatique', es: 'Los pioneros de la informática', ar: 'روّاد الحوسبة' },
        d: { en: 'Short portraits of the people who built the field — so children see who does this work, and that they could too.',
             fr: 'De courts portraits de ceux qui ont bâti le domaine — l\'enfant voit qui fait ce métier, et qu\'il le pourrait aussi.',
             es: 'Retratos breves de quienes construyeron el campo — el niño ve quién hace este trabajo, y que él también podría.',
             ar: 'صور مختصرة لمن أسّسوا هذا المجال — ليرى الطفل من يقوم بهذا العمل، وأنه يستطيع مثلهم.' } },
    ],
    faq: {
      en: [
        ['At what age can a child start CodoKids?', 'From about 4. The CodeQuest instructions are icons rather than words, so a child who cannot read yet can already solve the first levels. The topics and later levels suit up to about 13.'],
        ['Does my child need to be good at maths?', 'No. Coding builds the same thinking maths uses — sequencing, logic, patterns — so it usually helps maths rather than requiring it.'],
        ['Is there any real programming language?', 'Not yet. CodoKids deliberately stops at block-based logic, which is the right first step; text languages come later, once the thinking is in place.'],
        ['Does CodoKids work offline?', 'Yes. All 40 levels, the nine topics and every game are stored in the app.'],
      ],
      fr: [
        ['À quel âge un enfant peut-il commencer CodoKids ?', 'Dès 4 ans environ. Les instructions de CodeQuest sont des icônes et non des mots : un enfant qui ne lit pas encore résout déjà les premiers niveaux. Les sujets et les niveaux avancés vont jusqu\'à 13 ans environ.'],
        ['Mon enfant doit-il être bon en maths ?', 'Non. Le codage développe la même pensée que les maths — ordre, logique, motifs — il aide donc les maths plus qu\'il ne les exige.'],
        ['Y a-t-il un vrai langage de programmation ?', 'Pas encore. CodoKids s\'arrête volontairement à la logique par blocs, qui est la bonne première étape ; les langages textuels viendront ensuite, une fois la pensée en place.'],
        ['CodoKids fonctionne-t-il hors ligne ?', 'Oui. Les 40 niveaux, les neuf sujets et tous les jeux sont stockés dans l\'application.'],
      ],
      es: [
        ['¿A qué edad puede empezar un niño con CodoKids?', 'Desde los 4 años aproximadamente. Las instrucciones de CodeQuest son iconos y no palabras, así que un niño que aún no lee ya resuelve los primeros niveles. Los temas y niveles avanzados llegan hasta unos 13 años.'],
        ['¿Mi hijo tiene que ser bueno en matemáticas?', 'No. Programar desarrolla el mismo pensamiento que usan las matemáticas — secuencia, lógica, patrones — así que suele ayudar a las matemáticas más que exigirlas.'],
        ['¿Hay algún lenguaje de programación real?', 'Todavía no. CodoKids se detiene a propósito en la lógica por bloques, que es el primer paso correcto; los lenguajes de texto vienen después, cuando el pensamiento ya está formado.'],
        ['¿CodoKids funciona sin conexión?', 'Sí. Los 40 niveles, los nueve temas y todos los juegos están dentro de la app.'],
      ],
      ar: [
        ['في أي عمر يبدأ الطفل مع CodoKids؟', 'من نحو 4 سنوات. أوامر CodeQuest أيقونات لا كلمات، فالطفل الذي لا يقرأ بعد يحلّ المستويات الأولى فعلًا. أما المواضيع والمستويات المتقدّمة فتناسب حتى نحو 13 سنة.'],
        ['هل يجب أن يكون طفلي متفوّقًا في الرياضيات؟', 'لا. البرمجة تبني التفكير نفسه الذي تستعمله الرياضيات — الترتيب والمنطق والأنماط — فهي غالبًا تساعد الرياضيات لا تشترطها.'],
        ['هل فيه لغة برمجة حقيقية؟', 'ليس بعد. يتوقّف CodoKids عمدًا عند المنطق بالمكعّبات، وهو الخطوة الأولى الصحيحة؛ واللغات النصّية تأتي لاحقًا بعد ترسّخ التفكير.'],
        ['هل يعمل CodoKids دون إنترنت؟', 'نعم. المستويات الأربعون والمواضيع التسعة وكل الألعاب مخزّنة داخل التطبيق.'],
      ],
    },
  },

  /* ── 4 · GeoKids ───────────────────────────────────────────────────── */
  {
    slug: 'geokids', name: 'GeoKids', pkg: 'com.vsmedia.geokids',
    file: 'geokids.png', color: '#7CB342', emoji: '🌍', dl: 'New', released: '2026-07-10',
    subject: { en: 'Geography', fr: 'Géographie', es: 'Geografía', ar: 'الجغرافيا' },
    tagline: { en: 'Learn geography by playing', fr: 'Apprends la géographie en jouant',
               es: 'Aprende geografía jugando', ar: 'تعلّم الجغرافيا باللعب' },
    lede: {
      en: 'GeoKids turns the world into something a child can hold: nine topics from continents and oceans to landmarks, weather and cultures, plus a World Atlas to browse country by country. Flags, maps and seven kinds of game make the names stick — offline, on any Android device.',
      fr: "GeoKids met le monde à la portée d'un enfant : neuf sujets, des continents et des océans aux monuments, au climat et aux cultures, plus un Atlas mondial à parcourir pays par pays. Drapeaux, cartes et sept types de jeux font retenir les noms — hors ligne, sur tout appareil Android.",
      es: 'GeoKids pone el mundo al alcance de un niño: nueve temas, de los continentes y océanos a los monumentos, el clima y las culturas, más un Atlas mundial para recorrer país por país. Banderas, mapas y siete tipos de juego fijan los nombres — sin conexión, en cualquier Android.',
      ar: 'يضع GeoKids العالم بين يدي الطفل: تسعة مواضيع من القارّات والمحيطات إلى المعالم والطقس والثقافات، مع أطلس عالمي يُتصفّح بلدًا بلدًا. الأعلام والخرائط وسبعة أنواع من الألعاب ترسّخ الأسماء — دون إنترنت، على أي جهاز أندرويد.',
    },
    stats: [
      { v: '9', l: { en: 'Topics', fr: 'Sujets', es: 'Temas', ar: 'مواضيع' } },
      { v: '7', l: { en: 'Game types', fr: 'Types de jeux', es: 'Tipos de juego', ar: 'أنواع ألعاب' } },
      { v: '4–12', l: { en: 'Ages', fr: 'Âges', es: 'Edades', ar: 'الأعمار' } },
      { v: '100%', l: { en: 'Offline', fr: 'Hors ligne', es: 'Sin conexión', ar: 'دون إنترنت' } },
    ],
    features: [
      { i: '🗺️', t: { en: 'A World Atlas to browse', fr: 'Un Atlas mondial à parcourir', es: 'Un Atlas mundial para recorrer', ar: 'أطلس عالمي للتصفّح' },
        d: { en: 'Country by country: the flag, where it sits on the map and what makes it worth knowing.',
             fr: 'Pays par pays : le drapeau, sa place sur la carte et ce qui vaut la peine d\'être connu.',
             es: 'País por país: la bandera, su lugar en el mapa y lo que merece la pena saber.',
             ar: 'بلدًا بلدًا: العلم وموقعه على الخريطة وما يستحقّ أن يُعرف عنه.' } },
      { i: '🌎', t: { en: 'Nine topics', fr: 'Neuf sujets', es: 'Nueve temas', ar: 'تسعة مواضيع' },
        d: { en: 'Continents, countries, landmarks, maps, nature, oceans, weather, transport and cultures.',
             fr: 'Continents, pays, monuments, cartes, nature, océans, climat, transports et cultures.',
             es: 'Continentes, países, monumentos, mapas, naturaleza, océanos, clima, transporte y culturas.',
             ar: 'القارّات والبلدان والمعالم والخرائط والطبيعة والمحيطات والطقس والنقل والثقافات.' } },
      { i: '🚩', t: { en: 'Flags and capitals', fr: 'Drapeaux et capitales', es: 'Banderas y capitales', ar: 'أعلام وعواصم' },
        d: { en: 'The classic memory work, made playable — match flag to country, country to capital, capital to continent.',
             fr: 'Le travail de mémoire classique, rendu jouable — associer drapeau et pays, pays et capitale, capitale et continent.',
             es: 'El clásico trabajo de memoria, hecho juego — unir bandera y país, país y capital, capital y continente.',
             ar: 'عمل الحفظ التقليدي في صورة لعبة — وصل العلم بالبلد، والبلد بالعاصمة، والعاصمة بالقارّة.' } },
      { i: '🎮', t: { en: 'Seven kinds of game', fr: 'Sept types de jeux', es: 'Siete tipos de juego', ar: 'سبعة أنواع من الألعاب' },
        d: { en: 'Quiz, true-or-false, memory, matching, drag-and-drop, odd-one-out and puzzles for every topic.',
             fr: 'Quiz, vrai ou faux, mémoire, association, glisser-déposer, intrus et puzzles pour chaque sujet.',
             es: 'Quiz, verdadero o falso, memoria, asociación, arrastrar y soltar, intruso y puzles para cada tema.',
             ar: 'اختبار وصح/خطأ وذاكرة وتوصيل وسحب وإفلات واستبعاد الدخيل وأحاجٍ لكل موضوع.' } },
      { i: '🧭', t: { en: 'Explorers and their journeys', fr: 'Les explorateurs et leurs voyages', es: 'Exploradores y sus viajes', ar: 'المستكشفون ورحلاتهم' },
        d: { en: 'The people who mapped the world, told as short stories rather than dates to memorise.',
             fr: 'Ceux qui ont cartographié le monde, racontés en courtes histoires plutôt qu\'en dates à retenir.',
             es: 'Quienes cartografiaron el mundo, contados como relatos breves y no como fechas que memorizar.',
             ar: 'من رسموا خرائط العالم، في حكايات قصيرة بدل تواريخ تُحفظ.' } },
      { i: '🎨', t: { en: 'Colouring & culture', fr: 'Coloriage et cultures', es: 'Colorear y culturas', ar: 'تلوين وثقافات' },
        d: { en: 'Colour flags and landmarks, and meet how children live elsewhere — geography as people, not only places.',
             fr: 'Colorier drapeaux et monuments, et découvrir comment vivent les enfants ailleurs — la géographie comme des gens, pas seulement des lieux.',
             es: 'Colorear banderas y monumentos, y descubrir cómo viven los niños en otros lugares — geografía como personas, no solo lugares.',
             ar: 'تلوين الأعلام والمعالم، والتعرّف على حياة الأطفال في أماكن أخرى — الجغرافيا بشرٌ لا أماكن فقط.' } },
    ],
    faq: {
      en: [
        ['What age is GeoKids for?', 'Roughly 4 to 12. Younger children start with flags and continents as colours and shapes; older ones move to maps, capitals and the atlas.'],
        ['What does the World Atlas include?', 'A country-by-country browser with flags, position on the map and key facts, built to be explored freely rather than followed in order.'],
        ['Does GeoKids help with school geography?', 'Yes — continents, oceans, capitals, landmarks and map reading are the core of primary geography, and the games target exactly that vocabulary.'],
        ['Does it work offline?', 'Yes. The atlas, all nine topics and every game are stored in the app; no connection is needed.'],
      ],
      fr: [
        ['À quel âge s\'adresse GeoKids ?', 'Environ 4 à 12 ans. Les plus jeunes commencent par les drapeaux et les continents comme couleurs et formes ; les plus grands passent aux cartes, aux capitales et à l\'atlas.'],
        ['Que contient l\'Atlas mondial ?', 'Un navigateur pays par pays avec drapeaux, position sur la carte et informations clés, conçu pour être exploré librement plutôt que suivi dans l\'ordre.'],
        ['GeoKids aide-t-il pour la géographie scolaire ?', 'Oui — continents, océans, capitales, monuments et lecture de cartes forment le cœur de la géographie au primaire, et les jeux visent précisément ce vocabulaire.'],
        ['Fonctionne-t-il hors ligne ?', 'Oui. L\'atlas, les neuf sujets et tous les jeux sont dans l\'application ; aucune connexion n\'est nécessaire.'],
      ],
      es: [
        ['¿Para qué edad es GeoKids?', 'De unos 4 a 12 años. Los más pequeños empiezan con banderas y continentes como colores y formas; los mayores pasan a mapas, capitales y el atlas.'],
        ['¿Qué incluye el Atlas mundial?', 'Un navegador país por país con banderas, posición en el mapa y datos clave, pensado para explorarse libremente y no para seguirse en orden.'],
        ['¿GeoKids ayuda con la geografía del colegio?', 'Sí — continentes, océanos, capitales, monumentos y lectura de mapas son el núcleo de la geografía de primaria, y los juegos trabajan justo ese vocabulario.'],
        ['¿Funciona sin conexión?', 'Sí. El atlas, los nueve temas y todos los juegos están en la app; no hace falta conexión.'],
      ],
      ar: [
        ['ما العمر المناسب لتطبيق GeoKids؟', 'من نحو 4 إلى 12 سنة. الأصغر يبدؤون بالأعلام والقارّات كألوان وأشكال، والأكبر ينتقلون إلى الخرائط والعواصم والأطلس.'],
        ['ماذا يضمّ الأطلس العالمي؟', 'متصفّحًا بلدًا بلدًا فيه الأعلام والموقع على الخريطة ومعلومات أساسية، مصمّمًا للاستكشاف الحرّ لا للاتّباع بترتيب.'],
        ['هل يساعد GeoKids في جغرافيا المدرسة؟', 'نعم — القارّات والمحيطات والعواصم والمعالم وقراءة الخرائط هي صلب الجغرافيا الابتدائية، والألعاب تستهدف هذه المفردات بالضبط.'],
        ['هل يعمل دون إنترنت؟', 'نعم. الأطلس والمواضيع التسعة وكل الألعاب داخل التطبيق، ولا حاجة إلى اتصال.'],
      ],
    },
  },

  /* ── 5–10 · the language apps ──────────────────────────────────────── */
  languageApp({ slug: 'englokids', name: 'EngloKids', pkg: 'com.vsmedia.englokids',
    file: 'englokids.png', color: '#DC2626', emoji: '🇬🇧', dl: '20K+', released: '2026-03-01', lessons: 101,
    target: { en: 'English', fr: 'Anglais', es: 'Inglés', ar: 'الإنجليزية' },
    leFr: "l'anglais", elEs: 'inglés', adjFr: 'anglais', adjEs: 'inglesas' }),

  languageApp({ slug: 'francokids', name: 'FrancoKids', pkg: 'com.vsmedia.francokids',
    file: 'francokids.png', color: '#2563EB', emoji: '🇫🇷', dl: '15K+', released: '2026-03-01', lessons: 101,
    target: { en: 'French', fr: 'Français', es: 'Francés', ar: 'الفرنسية' },
    leFr: 'le français', elEs: 'francés', adjFr: 'français', adjEs: 'francesas' }),

  languageApp({ slug: 'spanokids', name: 'SpanoKids', pkg: 'com.vsmedia.spanokids',
    file: 'spanokids.png', color: '#F59E0B', emoji: '🇪🇸', dl: '12K+', released: '2026-03-01', lessons: 101,
    target: { en: 'Spanish', fr: 'Espagnol', es: 'Español', ar: 'الإسبانية' },
    leFr: "l'espagnol", elEs: 'español', adjFr: 'espagnols', adjEs: 'españolas' }),

  languageApp({ slug: 'arabikids', name: 'ArabiKids', pkg: 'com.vsmedia.arabikids',
    file: 'arabikids.png', color: '#6816AD', emoji: '🇲🇦', dl: '18K+', released: '2026-03-01', lessons: 101,
    target: { en: 'Arabic', fr: 'Arabe', es: 'Árabe', ar: 'العربية' },
    leFr: "l'arabe", elEs: 'árabe', adjFr: 'arabes', adjEs: 'árabes' }),

  languageApp({ slug: 'germokids', name: 'GermoKids', pkg: 'com.vsmedia.germokids',
    file: 'germokids.png', color: '#1A1A1A', emoji: '🇩🇪', dl: '8K+', released: '2026-06-01', lessons: 100,
    target: { en: 'German', fr: 'Allemand', es: 'Alemán', ar: 'الألمانية' },
    leFr: "l'allemand", elEs: 'alemán', adjFr: 'allemands', adjEs: 'alemanas' }),

  languageApp({ slug: 'chinokids', name: 'ChinoKids', pkg: 'com.vsmedia.chinokids',
    file: 'chinokids.png', color: '#DC2626', emoji: '🇨🇳', dl: '6K+', released: '2026-05-01', lessons: 100,
    target: { en: 'Chinese', fr: 'Chinois', es: 'Chino', ar: 'الصينية' },
    leFr: 'le chinois', elEs: 'chino', adjFr: 'chinois', adjEs: 'chinas' }),
];
