/* ═══════════════════════════════════════════════════════════════════════
   Kids Learning Hub — worksheet page content
   ═══════════════════════════════════════════════════════════════════════
   The worksheet generators are useful but carry ~550 characters of visible
   text each. Twenty-six near-identical pages of that size read as thin,
   duplicated content — which is why they do not rank despite targeting
   high-demand queries ("free printable multiplication worksheets" etc).

   This file adds the missing half: what the skill is, how to work through
   it, what age it suits, and the questions parents actually ask. Content
   is written per topic — templated filler across 26 pages would make the
   thin-content problem worse, not better.

   Consumed by tools/build-worksheets.js.

   Topics not listed here are left exactly as they are — the tool only
   touches what it has real content for. Add entries over time.
   ═══════════════════════════════════════════════════════════════════════ */
'use strict';

module.exports = [

/* ── 1 · multiplication ────────────────────────────────────────────── */
{
  slug: 'multiplication',
  meta: {
    en: { title: 'Free Printable Times Tables Worksheets (PDF, A4) | Kids Learning Hub',
          desc: 'Unlimited free multiplication worksheets to print: tables 1–12, a fresh A4 sheet every click. Plus how to teach times tables in the right order. No sign-up.' },
    fr: { title: 'Fiches de tables de multiplication à imprimer (A4, gratuit) | Kids Learning Hub',
          desc: 'Fiches de multiplication gratuites à imprimer : tables de 1 à 12, une nouvelle feuille A4 à chaque clic, et l\'ordre d\'apprentissage conseillé. Sans inscription.' },
    es: { title: 'Fichas de tablas de multiplicar para imprimir (A4, gratis) | Kids Learning Hub',
          desc: 'Fichas de multiplicación gratis para imprimir: tablas del 1 al 12, una hoja A4 nueva con cada clic, y en qué orden enseñarlas. Sin registro.' },
    ar: { title: 'أوراق عمل جداول الضرب للطباعة (A4) | Kids Learning Hub',
          desc: 'أوراق ضرب مجانية للطباعة: جداول من 1 إلى 12، وورقة A4 جديدة مع كل نقرة، مع الترتيب الصحيح لتعليم الجداول. دون تسجيل.' },
  }, emoji: '✖️', ages: '7–11',
  lede: {
    en: 'Times tables are the last piece of arithmetic that has to become automatic. A child who still counts up to work out 7 × 8 will struggle with division, fractions and long multiplication later — not because those are harder, but because the working memory is already full. These sheets exist to move recall from counting to knowing.',
    fr: "Les tables de multiplication sont le dernier morceau du calcul qui doit devenir automatique. Un enfant qui compte encore pour trouver 7 × 8 peinera plus tard en division, en fractions et en multiplication posée — non parce que c'est plus difficile, mais parce que sa mémoire de travail est déjà saturée. Ces fiches servent à passer du comptage à la connaissance.",
    es: 'Las tablas de multiplicar son la última pieza del cálculo que debe volverse automática. Un niño que aún cuenta para resolver 7 × 8 tendrá dificultades después con la división, las fracciones y la multiplicación en columna: no porque sean más difíciles, sino porque su memoria de trabajo ya está llena. Estas fichas sirven para pasar de contar a saber.',
    ar: 'جداول الضرب آخر ما يجب أن يصير تلقائيًا في الحساب. والطفل الذي ما زال يعدّ ليحسب 7 × 8 سيتعثّر لاحقًا في القسمة والكسور والضرب العمودي — لا لأنها أصعب، بل لأن ذاكرته العاملة ممتلئة أصلًا. وهذه الأوراق وُضعت لينتقل من العدّ إلى المعرفة.',
  },
  how: {
    en: ['Start with the 2, 5 and 10 tables — their patterns are visible, so early wins come fast.',
         'Then 3 and 4, and leave 6, 7, 8 and 9 for last: by then half of them are already known in reverse.',
         'Ten minutes a day beats an hour on Sunday. Recall is built by frequency, not duration.',
         'Print a fresh sheet each time rather than repeating one — memorising a page is not the same as knowing the facts.'],
    fr: ["Commencez par les tables de 2, 5 et 10 : leurs régularités se voient, les premières réussites arrivent vite.",
         'Puis 3 et 4, en gardant 6, 7, 8 et 9 pour la fin : la moitié sera déjà connue à l\'envers.',
         "Dix minutes par jour valent mieux qu'une heure le dimanche. La mémorisation se construit par la fréquence.",
         "Imprimez une nouvelle fiche à chaque fois plutôt que de refaire la même : retenir une page n'est pas connaître les faits."],
    es: ['Empieza por las tablas del 2, 5 y 10: sus patrones se ven, así que los primeros logros llegan rápido.',
         'Después el 3 y el 4, dejando el 6, 7, 8 y 9 para el final: para entonces la mitad ya se sabe al revés.',
         'Diez minutos al día valen más que una hora el domingo. La memoria se construye con frecuencia.',
         'Imprime una ficha nueva cada vez en lugar de repetir la misma: memorizar una página no es saber los hechos.'],
    ar: ['ابدأ بجداول 2 و5 و10 — أنماطها ظاهرة، فتأتي الانتصارات الأولى بسرعة.',
         'ثم 3 و4، واترك 6 و7 و8 و9 للأخير: عندها يكون نصفها معروفًا بالمقلوب.',
         'عشر دقائق يوميًا أفضل من ساعة يوم الأحد. الحفظ يُبنى بالتكرار المنتظم لا بطول الجلسة.',
         'اطبع ورقة جديدة في كل مرة بدل إعادة الورقة نفسها — حفظ الصفحة ليس كمعرفة الحقائق.'],
  },
  faq: {
    en: [['In what order should a child learn the times tables?', 'Start with 2, 5 and 10 because their patterns are obvious, then 3 and 4, and finish with 6, 7, 8 and 9. By the time you reach the hard ones, most have already appeared in reverse — a child who knows 4 × 7 already knows 7 × 4.'],
         ['At what age should times tables be mastered?', 'Most children learn them between 7 and 9 and are fluent by about 10. Starting earlier rarely helps; short, regular practice matters far more than an early start.'],
         ['How long does it take to memorise them?', 'With about ten minutes of daily practice, most children are secure within two to three months. Progress is uneven — the 6, 7 and 8 tables usually take as long as all the others combined.']],
    fr: [['Dans quel ordre apprendre les tables ?', "Commencez par 2, 5 et 10, dont les régularités sont évidentes, puis 3 et 4, et terminez par 6, 7, 8 et 9. Arrivé aux difficiles, la plupart sont déjà connues à l'envers : qui sait 4 × 7 sait déjà 7 × 4."],
         ['À quel âge les tables doivent-elles être acquises ?', "La plupart des enfants les apprennent entre 7 et 9 ans et les maîtrisent vers 10 ans. Commencer plus tôt aide rarement ; la régularité compte bien plus que la précocité."],
         ['Combien de temps faut-il pour les mémoriser ?', "Avec une dizaine de minutes par jour, la plupart des enfants les maîtrisent en deux à trois mois. La progression est inégale : les tables de 6, 7 et 8 prennent souvent autant de temps que toutes les autres réunies."]],
    es: [['¿En qué orden aprender las tablas?', 'Empieza por el 2, 5 y 10, cuyos patrones son evidentes, después el 3 y el 4, y termina con el 6, 7, 8 y 9. Al llegar a las difíciles, la mayoría ya se conocen al revés: quien sabe 4 × 7 ya sabe 7 × 4.'],
         ['¿A qué edad deben dominarse?', 'La mayoría las aprende entre los 7 y los 9 años y las domina hacia los 10. Empezar antes rara vez ayuda; la constancia importa mucho más que la precocidad.'],
         ['¿Cuánto se tarda en memorizarlas?', 'Con unos diez minutos diarios, la mayoría las domina en dos o tres meses. El avance es desigual: las tablas del 6, 7 y 8 suelen costar tanto como todas las demás juntas.']],
    ar: [['بأي ترتيب يتعلّم الطفل جداول الضرب؟', 'ابدأ بجداول 2 و5 و10 لوضوح أنماطها، ثم 3 و4، واختم بـ6 و7 و8 و9. وعند الوصول إلى الصعبة يكون أغلبها معروفًا بالمقلوب: من يعرف 4 × 7 يعرف 7 × 4.'],
         ['في أي عمر يُتقن الطفل الجداول؟', 'يتعلّمها معظم الأطفال بين 7 و9 سنوات ويتقنونها نحو العاشرة. والبدء المبكر نادرًا ما يفيد؛ فالانتظام أهمّ بكثير من التبكير.'],
         ['كم يستغرق حفظها؟', 'بنحو عشر دقائق يوميًا يتقنها معظم الأطفال خلال شهرين إلى ثلاثة. والتقدّم غير متساوٍ: جداول 6 و7 و8 تأخذ عادة وقتًا يوازي بقية الجداول مجتمعة.']],
  },
},

/* ── 2 · addition ──────────────────────────────────────────────────── */
{
  slug: 'addition',
  meta: {
    en: { title: 'Free Printable Addition Worksheets for Kids (A4) | Kids Learning Hub',
          desc: 'Unlimited free addition worksheets: sums to 10, 20 or 100, a fresh A4 sheet every click - plus what to practise first and when. No sign-up, no download.' },
    fr: { title: 'Fiches d\'addition à imprimer pour enfants (A4, gratuit) | Kids Learning Hub',
          desc: 'Fiches d\'addition gratuites : sommes jusqu\'à 10, 20 ou 100, une nouvelle feuille A4 à chaque clic, et par quoi commencer. Sans inscription.' },
    es: { title: 'Fichas de sumas para imprimir para niños (A4, gratis) | Kids Learning Hub',
          desc: 'Fichas de sumas gratis: hasta 10, 20 o 100, una hoja A4 nueva con cada clic, y por dónde empezar. Sin registro ni descargas.' },
    ar: { title: 'أوراق عمل الجمع للطباعة للأطفال (A4) | Kids Learning Hub',
          desc: 'أوراق جمع مجانية: ضمن 10 أو 20 أو 100، وورقة A4 جديدة مع كل نقرة، مع ما يجب تدريبه أولاً. دون تسجيل.' },
  }, emoji: '➕', ages: '5–9',
  lede: {
    en: 'Addition is where arithmetic starts, and where two different skills get confused. Finding the answer by counting on fingers is a strategy; knowing that 6 + 7 is 13 without pausing is a fact. Children need both, in that order — and the move between them happens through repetition with small numbers, not through bigger ones.',
    fr: "L'addition est le point de départ du calcul, et l'endroit où deux compétences se confondent. Trouver le résultat en comptant sur ses doigts est une stratégie ; savoir que 6 + 7 font 13 sans hésiter est un fait. L'enfant a besoin des deux, dans cet ordre — et le passage se fait par la répétition sur de petits nombres, pas par des nombres plus grands.",
    es: 'La suma es donde empieza el cálculo, y donde se confunden dos habilidades distintas. Hallar el resultado contando con los dedos es una estrategia; saber que 6 + 7 son 13 sin dudar es un hecho. El niño necesita ambas, en ese orden, y el paso se da repitiendo con números pequeños, no con números mayores.',
    ar: 'الجمع هو بداية الحساب، وموضع الخلط بين مهارتين مختلفتين. إيجاد الناتج بالعدّ على الأصابع استراتيجية، ومعرفة أن 6 + 7 تساوي 13 دون توقّف حقيقة محفوظة. ويحتاج الطفل إلى الاثنتين بهذا الترتيب — والانتقال بينهما يحدث بالتكرار على الأعداد الصغيرة، لا بالأعداد الأكبر.',
  },
  how: {
    en: ['Stay within 10 until it is effortless, then move to 20, then to 100. Widening the range too early slows everything down.',
         'Teach the pairs that make 10 (3 + 7, 4 + 6) as their own thing — almost every later shortcut depends on them.',
         'Let a child who is stuck count. Removing the fallback creates anxiety, not fluency.',
         'Mark only what is right. The blank ones are the lesson, and they need no red ink to be visible.'],
    fr: ["Restez sous 10 jusqu'à ce que ce soit sans effort, puis passez à 20, puis à 100. Élargir trop tôt ralentit tout.",
         'Enseignez les paires qui font 10 (3 + 7, 4 + 6) comme un savoir à part : presque toutes les astuces ultérieures en dépendent.',
         "Laissez compter l'enfant bloqué. Retirer ce recours crée de l'anxiété, pas de l'aisance.",
         "Ne corrigez que ce qui est juste. Les cases vides sont la leçon, et n'ont pas besoin d'encre rouge pour se voir."],
    es: ['Quédate dentro del 10 hasta que salga sin esfuerzo, luego pasa al 20 y después al 100. Ampliar demasiado pronto lo frena todo.',
         'Enseña las parejas que suman 10 (3 + 7, 4 + 6) como algo propio: casi todos los atajos posteriores dependen de ellas.',
         'Deja contar al niño que se atasca. Quitarle ese apoyo genera ansiedad, no soltura.',
         'Corrige solo lo que está bien. Los huecos son la lección y no necesitan tinta roja para verse.'],
    ar: ['ابقَ ضمن العشرة حتى تصير بلا جهد، ثم انتقل إلى 20 ثم إلى 100. والتوسّع المبكر يبطّئ كل شيء.',
         'علّم الأزواج التي تكوّن 10 (3 + 7، 4 + 6) كمعرفة مستقلّة، فأغلب الاختصارات اللاحقة تعتمد عليها.',
         'اترك الطفل المتعثّر يعدّ. فسحب هذا السند يولّد القلق لا الطلاقة.',
         'صحّح ما هو صحيح فقط. الفراغات هي الدرس، ولا تحتاج حبرًا أحمر لتظهر.'],
  },
  faq: {
    en: [['What age are addition worksheets for?', 'Roughly 5 to 9. Start with sums inside 10 at five or six, move to 20 once those are quick, and to 100 at about seven or eight.'],
         ['Should my child stop counting on their fingers?', 'Not by being told to. Finger counting fades on its own as facts become known. Taking it away early usually produces guessing and anxiety rather than faster recall.'],
         ['How many problems should one session have?', 'One sheet — around 24 problems — is enough for most children. If concentration goes before the sheet ends, stop there: a half sheet done well beats a full one done resentfully.']],
    fr: [["À quel âge conviennent ces fiches d'addition ?", "Environ 5 à 9 ans. Commencez par les sommes jusqu'à 10 vers 5–6 ans, passez à 20 quand elles sont rapides, puis à 100 vers 7–8 ans."],
         ['Mon enfant doit-il arrêter de compter sur ses doigts ?', "Pas sur ordre. Le comptage sur les doigts disparaît de lui-même à mesure que les faits sont sus. Le supprimer trop tôt produit des devinettes et de l'anxiété, pas une meilleure rapidité."],
         ['Combien de calculs par séance ?', "Une fiche — environ 24 calculs — suffit à la plupart des enfants. Si la concentration lâche avant la fin, arrêtez-vous là : une demi-fiche faite sérieusement vaut mieux qu'une fiche entière faite à contrecœur."]],
    es: [['¿Para qué edad son estas fichas de sumas?', 'Aproximadamente de 5 a 9 años. Empieza con sumas hasta 10 a los cinco o seis, pasa a 20 cuando salgan rápidas y a 100 hacia los siete u ocho.'],
         ['¿Mi hijo debe dejar de contar con los dedos?', 'No por orden. Contar con los dedos desaparece solo a medida que se saben los hechos. Quitarlo pronto suele producir adivinanzas y ansiedad, no más rapidez.'],
         ['¿Cuántas operaciones por sesión?', 'Una ficha —unas 24 operaciones— basta para la mayoría. Si la concentración se acaba antes, para ahí: media ficha bien hecha vale más que una entera hecha a disgusto.']],
    ar: [['ما العمر المناسب لأوراق الجمع؟', 'من نحو 5 إلى 9 سنوات. ابدأ بالجمع ضمن العشرة في سنّ الخامسة أو السادسة، وانتقل إلى 20 حين تصير سريعة، ثم إلى 100 نحو السابعة أو الثامنة.'],
         ['هل يجب أن يتوقّف طفلي عن العدّ بأصابعه؟', 'ليس بالأمر. العدّ بالأصابع يختفي وحده كلما ترسّخت الحقائق. وسحبه مبكرًا يولّد التخمين والقلق لا سرعة الاستدعاء.'],
         ['كم تمرينًا في الجلسة الواحدة؟', 'ورقة واحدة — نحو 24 تمرينًا — تكفي معظم الأطفال. وإن نفد التركيز قبل نهايتها فتوقّف: نصف ورقة بإتقان خير من ورقة كاملة على مضض.']],
  },
},

/* ── 3 · subtraction ───────────────────────────────────────────────── */
{
  slug: 'subtraction',
  meta: {
    en: { title: 'Free Printable Subtraction Worksheets (A4) | Kids Learning Hub',
          desc: 'Unlimited free subtraction worksheets to print, a fresh A4 sheet every click - plus why subtraction is harder than addition and how to fix it. No sign-up.' },
    fr: { title: 'Fiches de soustraction à imprimer (A4, gratuit) | Kids Learning Hub',
          desc: 'Fiches de soustraction gratuites à imprimer, une nouvelle feuille A4 à chaque clic — et pourquoi la soustraction pose plus de difficultés que l\'addition.' },
    es: { title: 'Fichas de restas para imprimir (A4, gratis) | Kids Learning Hub',
          desc: 'Fichas de restas gratis para imprimir, una hoja A4 nueva con cada clic — y por qué la resta cuesta más que la suma. Sin registro.' },
    ar: { title: 'أوراق عمل الطرح للطباعة (A4) | Kids Learning Hub',
          desc: 'أوراق طرح مجانية للطباعة، وورقة A4 جديدة مع كل نقرة - ولماذا الطرح أصعب من الجمع. دون تسجيل.' },
  }, emoji: '➖', ages: '5–10',
  lede: {
    en: 'Subtraction gives children more trouble than addition, and usually for one reason: it is taught as "take away" only. But 12 − 9 is far easier answered by asking how far 9 is from 12 than by removing nine things. Children who hold both meanings stop dreading the larger differences.',
    fr: "La soustraction pose plus de difficultés que l'addition, et souvent pour une seule raison : on ne l'enseigne que comme « enlever ». Pourtant 12 − 9 se résout bien plus facilement en cherchant la distance de 9 à 12 qu'en retirant neuf objets. L'enfant qui possède les deux sens cesse de redouter les grands écarts.",
    es: 'La resta da más problemas que la suma, y casi siempre por una razón: se enseña solo como «quitar». Pero 12 − 9 se resuelve mucho mejor preguntando qué distancia hay de 9 a 12 que retirando nueve objetos. El niño que maneja ambos sentidos deja de temer las diferencias grandes.',
    ar: 'الطرح يسبّب للأطفال صعوبة أكبر من الجمع، والسبب غالبًا واحد: أنه يُدرَّس بمعنى «الإزالة» فقط. لكن 12 − 9 تُحلّ أسهل بكثير بالسؤال عن المسافة بين 9 و12 من إزالة تسعة أشياء. والطفل الذي يملك المعنيين يكفّ عن الخوف من الفروق الكبيرة.',
  },
  how: {
    en: ['Say each problem two ways: "12 take away 9" and "how far from 9 to 12". Let the child pick whichever is easier.',
         'Master differences inside 10 before crossing it. The jump over ten is the real difficulty, not the size of the numbers.',
         'Use addition to check: if 12 − 9 = 3, then 3 + 9 should return 12. This turns checking into extra practice.',
         'Keep borrowing for later. Column subtraction only makes sense once single-digit differences are automatic.'],
    fr: ['Énoncez chaque calcul de deux façons : « 12 moins 9 » et « de 9 à 12, combien ? ». Laissez l\'enfant choisir la plus facile.',
         "Maîtrisez les écarts sous 10 avant de franchir la dizaine. Le passage de la dizaine est la vraie difficulté, pas la taille des nombres.",
         "Vérifiez par l'addition : si 12 − 9 = 3, alors 3 + 9 doit redonner 12. La vérification devient ainsi un exercice de plus.",
         "Gardez la retenue pour plus tard. La soustraction posée n'a de sens qu'une fois les écarts simples automatisés."],
    es: ['Di cada operación de dos formas: «12 menos 9» y «de 9 a 12, ¿cuánto hay?». Deja que el niño elija la más fácil.',
         'Domina las diferencias dentro del 10 antes de cruzarlo. El salto de la decena es la dificultad real, no el tamaño de los números.',
         'Comprueba con la suma: si 12 − 9 = 3, entonces 3 + 9 debe devolver 12. Así comprobar se convierte en práctica extra.',
         'Deja las llevadas para después. La resta en columna solo tiene sentido cuando las diferencias simples son automáticas.'],
    ar: ['اطرح كل تمرين بصيغتين: «12 ناقص 9» و«كم من 9 إلى 12؟»، ودع الطفل يختار الأسهل.',
         'أتقن الفروق ضمن العشرة قبل تجاوزها. فعبور العشرة هو الصعوبة الحقيقية لا حجم الأعداد.',
         'تحقّق بالجمع: إذا كان 12 − 9 = 3 فإن 3 + 9 يجب أن تعيد 12. وهكذا يصير التحقّق تمرينًا إضافيًا.',
         'أجّل الاستلاف. فالطرح العمودي لا معنى له قبل أن تصير الفروق البسيطة تلقائية.'],
  },
  faq: {
    en: [['Why is subtraction harder than addition?', 'Mostly because it is taught with one meaning. "Take away" works for 12 − 3 but is clumsy for 12 − 9. Teaching the "how far apart" meaning alongside it removes most of the difficulty.'],
         ['When should a child start borrowing?', 'Once single-digit differences are automatic, usually around 7 or 8. Introducing borrowing before that means learning a procedure on top of facts that are not secure — which is where most confusion begins.'],
         ['What age are these worksheets for?', 'About 5 to 10. Begin with differences inside 10, then within 20, then two-digit numbers.']],
    fr: [["Pourquoi la soustraction est-elle plus difficile que l'addition ?", "Surtout parce qu'on ne lui donne qu'un seul sens. « Enlever » convient pour 12 − 3 mais devient lourd pour 12 − 9. Enseigner aussi le sens « quel écart ? » supprime l'essentiel de la difficulté."],
         ["Quand introduire la retenue ?", "Une fois les écarts à un chiffre automatisés, généralement vers 7–8 ans. L'introduire avant revient à empiler une procédure sur des faits mal assurés — c'est là que naît la confusion."],
         ['À quel âge conviennent ces fiches ?', "Environ 5 à 10 ans. Commencez par les écarts sous 10, puis jusqu'à 20, puis les nombres à deux chiffres."]],
    es: [['¿Por qué la resta cuesta más que la suma?', 'Sobre todo porque se enseña con un solo sentido. «Quitar» sirve para 12 − 3 pero es torpe para 12 − 9. Enseñar también el sentido «qué distancia hay» elimina casi toda la dificultad.'],
         ['¿Cuándo empezar con las llevadas?', 'Cuando las diferencias de una cifra son automáticas, hacia los 7 u 8 años. Introducirlas antes es apilar un procedimiento sobre hechos poco firmes, y ahí empieza la confusión.'],
         ['¿Para qué edad son estas fichas?', 'De unos 5 a 10 años. Empieza con diferencias dentro del 10, luego hasta 20 y después con números de dos cifras.']],
    ar: [['لماذا الطرح أصعب من الجمع؟', 'غالبًا لأنه يُدرَّس بمعنى واحد. «الإزالة» تصلح لـ12 − 3 لكنها ثقيلة في 12 − 9. وتدريس معنى «كم الفرق» إلى جانبها يزيل معظم الصعوبة.'],
         ['متى يبدأ الطفل بالاستلاف؟', 'بعد أن تصير فروق الأرقام المفردة تلقائية، عادة نحو 7 أو 8 سنوات. وإدخاله قبل ذلك يعني تكديس إجراء فوق حقائق غير راسخة، ومن هنا يبدأ الالتباس.'],
         ['ما العمر المناسب لهذه الأوراق؟', 'من نحو 5 إلى 10 سنوات. ابدأ بالفروق ضمن العشرة، ثم حتى 20، ثم الأعداد ذات الرقمين.']],
  },
},

/* ── 4 · division ──────────────────────────────────────────────────── */
{
  slug: 'division',
  meta: {
    en: { title: 'Free Printable Division Worksheets for Kids (A4) | Kids Learning Hub',
          desc: 'Unlimited free division worksheets to print, a fresh A4 sheet every click - plus why times tables must come first. No sign-up, no download.' },
    fr: { title: 'Fiches de division à imprimer pour enfants (A4, gratuit) | Kids Learning Hub',
          desc: 'Fiches de division gratuites à imprimer, une nouvelle feuille A4 à chaque clic — et pourquoi les tables doivent venir d\'abord. Sans inscription.' },
    es: { title: 'Fichas de división para imprimir para niños (A4, gratis) | Kids Learning Hub',
          desc: 'Fichas de división gratis para imprimir, una hoja A4 nueva con cada clic — y por qué las tablas deben ir primero. Sin registro.' },
    ar: { title: 'أوراق عمل القسمة للطباعة (A4) | Kids Learning Hub',
          desc: 'أوراق قسمة مجانية للطباعة، وورقة A4 جديدة مع كل نقرة - ولماذا يجب أن تسبقها جداول الضرب. دون تسجيل.' },
  }, emoji: '➗', ages: '8–11',
  lede: {
    en: 'Division is the operation children meet last and understand least, because it is really two questions wearing one symbol. "Share 12 between 3" and "how many 3s fit into 12" give the same answer for different reasons. Both are worth saying out loud — and both collapse without secure times tables.',
    fr: "La division est l'opération rencontrée en dernier et la moins comprise, parce qu'elle pose en réalité deux questions sous un seul signe. « Partager 12 entre 3 » et « combien de fois 3 tient dans 12 » donnent le même résultat pour des raisons différentes. Les deux méritent d'être formulées — et les deux s'effondrent sans tables solides.",
    es: 'La división es la operación que se ve al final y la que menos se entiende, porque en realidad son dos preguntas bajo un mismo signo. «Repartir 12 entre 3» y «cuántos 3 caben en 12» dan el mismo resultado por razones distintas. Ambas merecen decirse en voz alta, y ambas se derrumban sin tablas firmes.',
    ar: 'القسمة آخر عملية يلتقيها الطفل وأقلّها فهمًا، لأنها في الحقيقة سؤالان تحت رمز واحد. «وزّع 12 على 3» و«كم مرّة يدخل 3 في 12» يعطيان الجواب نفسه لسببين مختلفين. ويستحقّ الاثنان أن يُقالا بصوت عالٍ — وكلاهما ينهار دون جداول ضرب راسخة.',
  },
  how: {
    en: ['Check the times tables first. Division practice on shaky tables teaches frustration, not division.',
         'Read each problem both ways: "12 shared between 3" and "how many 3s in 12".',
         'Start with facts that divide exactly. Remainders are a separate idea and deserve their own week.',
         'Point out that division undoes multiplication: 12 ÷ 3 = 4 because 4 × 3 = 12. Most children find this genuinely reassuring.'],
    fr: ['Vérifiez d\'abord les tables. S\'entraîner à diviser sur des tables fragiles enseigne la frustration, pas la division.',
         'Lisez chaque calcul dans les deux sens : « 12 partagé en 3 » et « combien de 3 dans 12 ».',
         'Commencez par les divisions exactes. Le reste est une autre idée et mérite sa propre semaine.',
         "Montrez que la division annule la multiplication : 12 ÷ 3 = 4 parce que 4 × 3 = 12. La plupart des enfants trouvent cela rassurant."],
    es: ['Comprueba antes las tablas. Practicar división con tablas frágiles enseña frustración, no división.',
         'Lee cada operación de las dos formas: «12 repartido entre 3» y «cuántos 3 hay en 12».',
         'Empieza por las divisiones exactas. El resto es otra idea y merece su propia semana.',
         'Señala que la división deshace la multiplicación: 12 ÷ 3 = 4 porque 4 × 3 = 12. A casi todos los niños les tranquiliza.'],
    ar: ['تحقّق من الجداول أولًا. فالتدريب على القسمة بجداول هشّة يعلّم الإحباط لا القسمة.',
         'اقرأ كل تمرين بالوجهين: «12 موزّعة على 3» و«كم 3 في 12».',
         'ابدأ بالقسمة التامّة. والباقي فكرة أخرى تستحقّ أسبوعها الخاص.',
         'بيّن أن القسمة تُلغي الضرب: 12 ÷ 3 = 4 لأن 4 × 3 = 12. ويجد أغلب الأطفال في ذلك طمأنينة حقيقية.'],
  },
  faq: {
    en: [['Does my child need the times tables before dividing?', 'Yes, and this is the single most common cause of trouble with division. 56 ÷ 7 is only answerable by someone who knows 7 × 8. If division is going badly, the fix is usually more table practice, not more division.'],
         ['What age is division for?', 'Typically 8 to 11. Sharing into equal groups can start earlier with objects, but written division belongs after the tables are secure.'],
         ['Should I teach remainders straight away?', 'No. Let exact divisions become comfortable first. Remainders introduce a second idea — what is left over — and mixing it in early makes both harder.']],
    fr: [["Faut-il connaître les tables avant de diviser ?", "Oui, et c'est de loin la cause la plus fréquente des difficultés en division. 56 ÷ 7 n'est accessible qu'à qui sait 7 × 8. Si la division coince, la solution est presque toujours de retravailler les tables."],
         ['À quel âge aborder la division ?', "Généralement 8 à 11 ans. Le partage en parts égales peut commencer plus tôt avec des objets, mais la division écrite vient après des tables solides."],
         ['Faut-il enseigner le reste tout de suite ?', "Non. Laissez d'abord les divisions exactes devenir confortables. Le reste introduit une seconde idée, et les mêler tôt rend les deux plus difficiles."]],
    es: [['¿Hace falta saber las tablas antes de dividir?', 'Sí, y es con diferencia la causa más común de dificultades con la división. 56 ÷ 7 solo lo resuelve quien sabe 7 × 8. Si la división va mal, la solución suele ser repasar tablas, no dividir más.'],
         ['¿Para qué edad es la división?', 'Normalmente de 8 a 11 años. Repartir en partes iguales puede empezar antes con objetos, pero la división escrita va después de tener tablas firmes.'],
         ['¿Enseño el resto desde el principio?', 'No. Deja que las divisiones exactas resulten cómodas primero. El resto añade una segunda idea, y mezclarlas pronto complica ambas.']],
    ar: [['هل يحتاج طفلي إلى الجداول قبل القسمة؟', 'نعم، وهذا أكثر أسباب التعثّر في القسمة شيوعًا. فـ56 ÷ 7 لا يحلّها إلا من يعرف 7 × 8. وإذا تعثّرت القسمة فالعلاج عادة مزيد من تمرين الجداول لا مزيد من القسمة.'],
         ['ما العمر المناسب للقسمة؟', 'عادة من 8 إلى 11 سنة. ويمكن أن يبدأ التوزيع بالتساوي أبكر بالأشياء الملموسة، أما القسمة المكتوبة فتأتي بعد رسوخ الجداول.'],
         ['هل أعلّم الباقي مباشرة؟', 'لا. دع القسمة التامّة تصير مريحة أولًا. فالباقي يضيف فكرة ثانية، وخلطهما مبكرًا يجعل كليهما أصعب.']],
  },
},

/* ── 5 · latin letters (tracing) ───────────────────────────────────── */
{
  slug: 'latin-letters',
  meta: {
    en: { title: 'Free Printable Letter Tracing Worksheets A–Z (A4) | Kids Learning Hub',
          desc: 'Free alphabet tracing worksheets to print: A–Z in the correct stroke order, a fresh A4 sheet every click - plus why direction matters more than neatness.' },
    fr: { title: 'Fiches d\'écriture des lettres A–Z à imprimer (A4, gratuit) | Kids Learning Hub',
          desc: 'Fiches de tracé des lettres gratuites : A–Z dans le bon sens de tracé, une nouvelle feuille A4 à chaque clic — et pourquoi le sens compte plus que la propreté.' },
    es: { title: 'Fichas de trazo de letras A–Z para imprimir (A4, gratis) | Kids Learning Hub',
          desc: 'Fichas de trazo de letras gratis: A–Z en el orden de trazo correcto, una hoja A4 nueva con cada clic — y por qué la dirección importa más que la pulcritud.' },
    ar: { title: 'أوراق تتبّع الحروف اللاتينية A-Z للطباعة (A4) | Kids Learning Hub',
          desc: 'أوراق تتبّع الحروف مجانية: من A إلى Z بترتيب الحركات الصحيح، وورقة A4 جديدة مع كل نقرة.' },
  }, emoji: '✏️', ages: '3–7',
  lede: {
    en: 'Handwriting is learned through the hand, not the eye. A child who copies a letter by drawing its outline may produce something that looks right and still be unable to write it fluently — because the stroke order is what becomes automatic, not the shape. These sheets are built for tracing in the correct direction.',
    fr: "L'écriture s'apprend par la main, pas par l'œil. Un enfant qui recopie une lettre en dessinant son contour peut produire quelque chose de correct sans savoir l'écrire couramment — car c'est l'ordre des tracés qui s'automatise, pas la forme. Ces fiches sont conçues pour un tracé dans le bon sens.",
    es: 'La escritura se aprende con la mano, no con el ojo. Un niño que copia una letra dibujando su contorno puede lograr algo correcto y aun así no escribirla con soltura, porque lo que se automatiza es el orden de los trazos, no la forma. Estas fichas están hechas para trazar en la dirección correcta.',
    ar: 'الكتابة تُتعلَّم باليد لا بالعين. والطفل الذي ينسخ الحرف برسم حدوده قد يُخرج شكلًا صحيحًا ويظلّ عاجزًا عن كتابته بطلاقة، لأن ما يصير تلقائيًا هو ترتيب الحركات لا الشكل. وهذه الأوراق مصمّمة للتتبّع في الاتجاه الصحيح.',
  },
  how: {
    en: ['Watch the direction, not the result. A letter drawn bottom-up looks fine on paper and slows writing for years.',
         'Trace with a finger before a pencil. The movement registers better without the difficulty of grip.',
         'Group letters by shape — c, o, a, d, g all begin with the same curve — rather than by alphabet order.',
         'Short and frequent wins: five minutes daily beats a long weekend session.'],
    fr: ["Surveillez le sens, pas le résultat. Une lettre tracée de bas en haut paraît correcte et ralentit l'écriture pendant des années.",
         'Faites tracer au doigt avant le crayon : le mouvement s\'imprime mieux sans la difficulté de la tenue.',
         'Regroupez les lettres par forme — c, o, a, d, g commencent par la même courbe — plutôt que par ordre alphabétique.',
         'Court et fréquent : cinq minutes par jour valent mieux qu\'une longue séance le week-end.'],
    es: ['Vigila la dirección, no el resultado. Una letra trazada de abajo arriba parece correcta y frena la escritura durante años.',
         'Que trace con el dedo antes que con el lápiz: el movimiento se fija mejor sin la dificultad del agarre.',
         'Agrupa las letras por forma —c, o, a, d, g empiezan con la misma curva— en vez de por orden alfabético.',
         'Corto y frecuente: cinco minutos diarios valen más que una sesión larga el fin de semana.'],
    ar: ['راقب الاتجاه لا النتيجة. فالحرف المرسوم من الأسفل إلى الأعلى يبدو سليمًا ويبطّئ الكتابة سنوات.',
         'دع الطفل يتتبّع بإصبعه قبل القلم؛ فالحركة ترسخ أفضل دون صعوبة الإمساك.',
         'اجمع الحروف حسب الشكل — c وo وa وd وg تبدأ بالانحناءة نفسها — بدل الترتيب الأبجدي.',
         'قصير ومتكرّر: خمس دقائق يوميًا أفضل من جلسة طويلة في العطلة.'],
  },
  faq: {
    en: [['What age should a child start tracing letters?', 'Around 3 or 4 for finger tracing and large shapes, and 5 to 6 for pencil work. Before that, drawing, cutting and threading build the hand strength that writing needs.'],
         ['Capitals or lower case first?', 'Capitals are easier — straight lines and simple curves — so most children start there. But lower case is what reading and writing actually use, so do not stay on capitals long.'],
         ['My child holds the pencil awkwardly. Does it matter?', 'It matters if it causes pain or slows writing. A relaxed grip with three fingers is the goal, but forcing a correction mid-task usually backfires. Adjust at the start of a session, then leave it alone.']],
    fr: [['À quel âge commencer le tracé des lettres ?', "Vers 3–4 ans pour le tracé au doigt et les grandes formes, 5–6 ans pour le crayon. Avant cela, dessiner, découper et enfiler construisent la force de main nécessaire."],
         ['Majuscules ou minuscules en premier ?', "Les majuscules sont plus faciles — traits droits et courbes simples — donc la plupart commencent par là. Mais ce sont les minuscules qui servent à lire et écrire : n'y restez pas trop longtemps."],
         ["Mon enfant tient mal son crayon. Est-ce grave ?", "C'est important si cela fait mal ou ralentit l'écriture. Une prise détendue à trois doigts est l'objectif, mais corriger en pleine tâche est souvent contre-productif. Ajustez en début de séance, puis laissez faire."]],
    es: [['¿A qué edad empezar a trazar letras?', 'Hacia los 3 o 4 años para trazar con el dedo y formas grandes, y de 5 a 6 para el lápiz. Antes, dibujar, recortar y ensartar construyen la fuerza de mano que la escritura necesita.'],
         ['¿Mayúsculas o minúsculas primero?', 'Las mayúsculas son más fáciles —líneas rectas y curvas simples— así que casi todos empiezan ahí. Pero las minúsculas son las que se usan al leer y escribir: no te quedes mucho en mayúsculas.'],
         ['Mi hijo agarra mal el lápiz. ¿Importa?', 'Importa si duele o frena la escritura. El objetivo es un agarre relajado con tres dedos, pero corregir en plena tarea suele salir mal. Ajusta al empezar la sesión y luego déjalo.']],
    ar: [['في أي عمر يبدأ الطفل تتبّع الحروف؟', 'نحو 3 أو 4 سنوات للتتبّع بالإصبع والأشكال الكبيرة، ومن 5 إلى 6 للعمل بالقلم. وقبل ذلك يبني الرسم والقصّ والتخريم قوّة اليد التي تحتاجها الكتابة.'],
         ['الحروف الكبيرة أم الصغيرة أولًا؟', 'الكبيرة أسهل — خطوط مستقيمة وانحناءات بسيطة — فيبدأ بها أغلب الأطفال. لكن الصغيرة هي المستعملة في القراءة والكتابة، فلا تُطل البقاء على الكبيرة.'],
         ['طفلي يمسك القلم بطريقة غريبة، هل هذا مهمّ؟', 'مهمّ إن سبّب ألمًا أو أبطأ الكتابة. والهدف إمساك مرتخٍ بثلاثة أصابع، لكن التصحيح في وسط النشاط يأتي بنتيجة عكسية غالبًا. عدّل في بداية الجلسة ثم اتركه.']],
  },
},

/* ── 6 · arabic letters ────────────────────────────────────────────── */
{
  slug: 'arabic-letters',
  meta: {
    en: { title: 'Free Printable Arabic Alphabet Tracing Worksheets (28 Letters) | Kids Learning Hub',
          desc: 'Free Arabic letter tracing worksheets to print: all 28 letters in their positions, a fresh A4 sheet every click - plus how to teach them by sound and family.' },
    fr: { title: 'Fiches d\'écriture des lettres arabes à imprimer (28 lettres) | Kids Learning Hub',
          desc: 'Fiches de tracé des lettres arabes gratuites : les 28 lettres et leurs positions, une nouvelle feuille A4 à chaque clic — et comment les enseigner par le son.' },
    es: { title: 'Fichas de trazo del alfabeto árabe para imprimir (28 letras) | Kids Learning Hub',
          desc: 'Fichas de trazo de letras árabes gratis: las 28 letras y sus posiciones, una hoja A4 nueva con cada clic — y cómo enseñarlas por sonido y por familias.' },
    ar: { title: 'أوراق تتبّع الحروف العربية للطباعة (28 حرفاً) | Kids Learning Hub',
          desc: 'أوراق تتبّع الحروف العربية مجانية: الحروف الـ28 بمواضعها، وورقة A4 جديدة مع كل نقرة - وكيف تعلّمها بالصوت.' },
  }, emoji: '🔤', ages: '4–8',
  lede: {
    en: 'Arabic asks something of a beginner that Latin script does not: most letters change shape depending on where they sit in the word. That sounds daunting, but children handle it well when the letter is taught as one family of forms rather than four separate things to memorise.',
    fr: "L'arabe demande au débutant ce que l'alphabet latin n'exige pas : la plupart des lettres changent de forme selon leur place dans le mot. Cela paraît intimidant, mais les enfants s'en sortent bien lorsque la lettre est enseignée comme une famille de formes plutôt que comme quatre choses distinctes à mémoriser.",
    es: 'El árabe pide al principiante algo que el alfabeto latino no: la mayoría de las letras cambian de forma según su lugar en la palabra. Suena intimidante, pero los niños lo llevan bien cuando la letra se enseña como una familia de formas y no como cuatro cosas distintas que memorizar.',
    ar: 'تطلب العربية من المبتدئ ما لا تطلبه الحروف اللاتينية: فأغلب الحروف تتغيّر أشكالها بحسب موقعها في الكلمة. يبدو ذلك مخيفًا، لكن الأطفال يتعاملون معه جيدًا حين يُدرَّس الحرف كعائلة أشكال واحدة لا كأربعة أشياء منفصلة تُحفظ.',
  },
  how: {
    en: ['Teach the sound before the name. A child who knows ب says "b" can blend and read; the name comes later without cost.',
         'Introduce a letter in all its positions at once, so the connection between the forms is obvious.',
         'Group letters that share a body and differ only in dots — ب ت ث, ج ح خ. It cuts the workload roughly in half.',
         'Always trace right to left. Direction matters more here than neatness.'],
    fr: ["Enseignez le son avant le nom. L'enfant qui sait que ب fait « b » peut fusionner et lire ; le nom viendra sans effort.",
         'Présentez la lettre dans toutes ses positions à la fois, pour que le lien entre les formes saute aux yeux.',
         'Regroupez les lettres au corps identique qui ne diffèrent que par les points — ب ت ث, ج ح خ. Cela réduit le travail de moitié.',
         'Tracez toujours de droite à gauche. Le sens compte ici plus que la propreté.'],
    es: ['Enseña el sonido antes que el nombre. El niño que sabe que ب suena «b» puede unir y leer; el nombre llegará sin coste.',
         'Presenta la letra en todas sus posiciones a la vez, para que el vínculo entre las formas resulte evidente.',
         'Agrupa las letras con el mismo cuerpo que solo se diferencian por los puntos —ب ت ث, ج ح خ—. Reduce el trabajo casi a la mitad.',
         'Traza siempre de derecha a izquierda. La dirección importa aquí más que la pulcritud.'],
    ar: ['علّم الصوت قبل الاسم. فمن يعرف أن «ب» صوتها بْ يستطيع الدمج والقراءة، ويأتي الاسم لاحقًا دون كلفة.',
         'قدّم الحرف بكل مواضعه دفعة واحدة ليظهر الرابط بين أشكاله.',
         'اجمع الحروف المتشابهة في الجسم والمختلفة في النقط — ب ت ث، ج ح خ. هذا يخفّف العبء إلى النصف تقريبًا.',
         'اكتب دائمًا من اليمين إلى اليسار. فالاتجاه هنا أهمّ من جمال الخط.'],
  },
  faq: {
    en: [['Is Arabic script hard for children to learn?', 'It looks harder than it is. The shapes are unfamiliar and most letters change form by position, but children treat that as a puzzle rather than a burden. Taught by sound and in letter families, most read simple words within a few months.'],
         ['Letter names or letter sounds first?', 'Sounds. Naming ب as "baa" does not help a child read the word; knowing it says "b" does. Names can be learned afterwards without slowing anything down.'],
         ['How long does it take to learn the 28 letters?', 'With roughly ten minutes of daily practice, most children recognise all 28 within six to eight weeks, and begin joining them into words shortly after.']],
    fr: [["L'écriture arabe est-elle difficile pour un enfant ?", "Elle paraît plus difficile qu'elle ne l'est. Les formes sont inhabituelles et la plupart des lettres changent selon la position, mais les enfants y voient un jeu plutôt qu'une charge. Enseignées par le son et par familles, la plupart lisent des mots simples en quelques mois."],
         ['Le nom ou le son des lettres en premier ?', "Le son. Appeler ب « bâ » n'aide pas à lire le mot ; savoir qu'elle fait « b » si. Les noms s'apprennent ensuite sans rien ralentir."],
         ['Combien de temps pour apprendre les 28 lettres ?', "Avec une dizaine de minutes par jour, la plupart des enfants reconnaissent les 28 lettres en six à huit semaines, et commencent à les relier peu après."]],
    es: [['¿Es difícil la escritura árabe para un niño?', 'Parece más difícil de lo que es. Las formas no son familiares y casi todas las letras cambian según la posición, pero los niños lo viven como un rompecabezas. Enseñadas por sonido y en familias, la mayoría lee palabras sencillas en pocos meses.'],
         ['¿Nombre o sonido de las letras primero?', 'El sonido. Llamar «ba» a ب no ayuda a leer la palabra; saber que suena «b» sí. Los nombres se aprenden después sin frenar nada.'],
         ['¿Cuánto se tarda en aprender las 28 letras?', 'Con unos diez minutos diarios, la mayoría reconoce las 28 en seis u ocho semanas, y empieza a unirlas poco después.']],
    ar: [['هل تعلّم الحروف العربية صعب على الأطفال؟', 'تبدو أصعب مما هي. الأشكال غير مألوفة وأغلب الحروف تتغيّر بحسب الموضع، لكن الأطفال يرونها أحجية لا عبئًا. وبتعليمها بالصوت وبعائلات الحروف يقرأ معظمهم كلمات بسيطة خلال أشهر قليلة.'],
         ['أسماء الحروف أم أصواتها أولًا؟', 'الأصوات. فتسمية «ب» بـ«باء» لا تساعد على قراءة الكلمة، أما معرفة أنها تنطق بْ فتساعد. وتأتي الأسماء لاحقًا دون أن تعطّل شيئًا.'],
         ['كم يستغرق تعلّم الحروف الثمانية والعشرين؟', 'بنحو عشر دقائق يوميًا يميّز معظم الأطفال الحروف الـ28 خلال ستة إلى ثمانية أسابيع، ثم يبدؤون وصلها بعد ذلك بقليل.']],
  },
},

/* ── 7 · numbers ───────────────────────────────────────────────────── */
{
  slug: 'numbers',
  meta: {
    en: { title: 'Free Printable Number Worksheets 1–20 for Kids (A4) | Kids Learning Hub',
          desc: 'Free number worksheets to print: writing and matching digits 1–20, a fresh A4 sheet every click - plus why counting and understanding are different skills.' },
    fr: { title: 'Fiches de chiffres 1–20 à imprimer pour enfants (A4, gratuit) | Kids Learning Hub',
          desc: 'Fiches de chiffres gratuites : écrire et associer les nombres de 1 à 20, une nouvelle feuille A4 à chaque clic — et pourquoi compter et dénombrer diffèrent.' },
    es: { title: 'Fichas de números 1–20 para imprimir para niños (A4, gratis) | Kids Learning Hub',
          desc: 'Fichas de números gratis: escribir y asociar del 1 al 20, una hoja A4 nueva con cada clic — y por qué contar y comprender son habilidades distintas.' },
    ar: { title: 'أوراق عمل الأرقام 1-20 للطباعة (A4) | Kids Learning Hub',
          desc: 'أوراق أرقام مجانية للطباعة: كتابة الأرقام من 1 إلى 20 وربطها بالمقادير، وورقة A4 جديدة مع كل نقرة.' },
  }, emoji: '🔢', ages: '3–6',
  lede: {
    en: 'Counting to twenty and understanding what twenty means are different achievements, and children reach them months apart. Reciting the sequence comes first and easily; knowing that the last number said is how many there are — and that the digit 7 stands for that quantity — is the real work these sheets support.',
    fr: "Compter jusqu'à vingt et comprendre ce que vingt signifie sont deux acquisitions distinctes, séparées par des mois. Réciter la suite vient d'abord et facilement ; savoir que le dernier nombre prononcé indique la quantité — et que le chiffre 7 représente cette quantité — est le vrai travail que soutiennent ces fiches.",
    es: 'Contar hasta veinte y entender qué significa veinte son logros distintos, separados por meses. Recitar la secuencia llega primero y con facilidad; saber que el último número dicho indica cuántos hay —y que el dígito 7 representa esa cantidad— es el trabajo real que apoyan estas fichas.',
    ar: 'العدّ حتى العشرين وفهم معنى العشرين إنجازان مختلفان يفصل بينهما أشهر. فترديد التسلسل يأتي أولًا وبسهولة، أما معرفة أن آخر عدد يُنطق هو المقدار — وأن الرقم 7 يمثّل هذا المقدار — فهو العمل الحقيقي الذي تدعمه هذه الأوراق.',
  },
  how: {
    en: ['Count real things, touching each one. Counting aloud without objects builds the rhyme, not the idea.',
         'Ask "how many?" after counting. A child who recounts from the start has not yet made the link.',
         'Write the digit next to the group it names, every time. The symbol needs to attach to a quantity.',
         'Stay inside 10 until it is solid. Ten understood is worth far more than twenty recited.'],
    fr: ['Comptez des objets réels en touchant chacun. Compter à voix haute sans objets construit la comptine, pas la notion.',
         "Demandez « combien ? » après avoir compté. L'enfant qui recompte depuis le début n'a pas encore fait le lien.",
         'Écrivez le chiffre à côté de la collection qu\'il désigne, à chaque fois. Le symbole doit se rattacher à une quantité.',
         'Restez sous 10 jusqu\'à ce que ce soit solide. Dix compris vaut bien plus que vingt récités.'],
    es: ['Cuenta cosas reales, tocando cada una. Contar en voz alta sin objetos construye la cantinela, no la idea.',
         'Pregunta «¿cuántos hay?» después de contar. El niño que vuelve a contar desde el principio aún no ha hecho la conexión.',
         'Escribe el dígito junto al grupo que nombra, siempre. El símbolo debe unirse a una cantidad.',
         'Quédate dentro del 10 hasta que esté firme. Diez comprendido vale mucho más que veinte recitados.'],
    ar: ['عُدّ أشياء حقيقية مع لمس كل واحدة. فالعدّ بصوت عالٍ دون أشياء يبني النشيد لا الفكرة.',
         'اسأل «كم؟» بعد العدّ. والطفل الذي يعيد العدّ من البداية لم يربط بعد.',
         'اكتب الرقم بجانب المجموعة التي يسمّيها في كل مرة. فالرمز يجب أن يرتبط بمقدار.',
         'ابقَ ضمن العشرة حتى ترسخ. فعشرة مفهومة خير من عشرين مردّدة.'],
  },
  faq: {
    en: [['When do children learn to write numbers?', 'Most recognise digits around 3 or 4 and write them between 4 and 6. Reversed digits are completely normal up to about seven and usually correct themselves.'],
         ['My child counts to 20 but cannot say how many. Why?', 'Because reciting and counting are different skills. The sequence is a rhyme; understanding that the last word said is the total takes longer. Counting real objects and asking "how many?" is what closes the gap.'],
         ['What age are these worksheets for?', 'About 3 to 6 — recognising digits, matching them to quantities and forming them correctly.']],
    fr: [['Quand les enfants apprennent-ils à écrire les chiffres ?', "La plupart les reconnaissent vers 3–4 ans et les écrivent entre 4 et 6 ans. Les chiffres inversés sont tout à fait normaux jusque vers 7 ans et se corrigent généralement seuls."],
         ["Mon enfant compte jusqu'à 20 mais ne sait pas dire combien. Pourquoi ?", "Parce que réciter et dénombrer sont deux compétences différentes. La suite est une comptine ; comprendre que le dernier mot dit le total demande plus de temps. Compter des objets réels en demandant « combien ? » comble cet écart."],
         ['À quel âge conviennent ces fiches ?', "Environ 3 à 6 ans : reconnaître les chiffres, les associer à des quantités et les former correctement."]],
    es: [['¿Cuándo aprenden los niños a escribir los números?', 'La mayoría reconoce los dígitos hacia los 3 o 4 años y los escribe entre los 4 y los 6. Los dígitos invertidos son normales hasta los siete y suelen corregirse solos.'],
         ['Mi hijo cuenta hasta 20 pero no sabe cuántos hay. ¿Por qué?', 'Porque recitar y contar son habilidades distintas. La secuencia es una cantinela; entender que la última palabra dice el total lleva más tiempo. Contar objetos reales preguntando «¿cuántos?» cierra esa brecha.'],
         ['¿Para qué edad son estas fichas?', 'De unos 3 a 6 años: reconocer dígitos, asociarlos a cantidades y formarlos correctamente.']],
    ar: [['متى يتعلّم الأطفال كتابة الأرقام؟', 'يميّز معظمهم الأرقام نحو 3 أو 4 سنوات ويكتبونها بين 4 و6. وقلب الأرقام أمر طبيعي تمامًا حتى نحو السابعة ويصحّح نفسه عادة.'],
         ['طفلي يعدّ حتى 20 لكنه لا يعرف كم العدد. لماذا؟', 'لأن الترديد والعدّ مهارتان مختلفتان. فالتسلسل نشيد، أما فهم أن آخر كلمة تدلّ على المجموع فيحتاج وقتًا أطول. وعدّ أشياء حقيقية مع سؤال «كم؟» هو ما يسدّ هذه الفجوة.'],
         ['ما العمر المناسب لهذه الأوراق؟', 'من نحو 3 إلى 6 سنوات: تمييز الأرقام وربطها بالمقادير وكتابتها بشكل صحيح.']],
  },
},

/* ── 8 · clock ─────────────────────────────────────────────────────── */
{
  slug: 'clock',
  meta: {
    en: { title: 'Free Printable Telling the Time Worksheets (Clock, A4) | Kids Learning Hub',
          desc: 'Free clock worksheets to print: whole hours, half past, quarters and five-minute steps, a fresh A4 sheet every click - plus the order to teach them in.' },
    fr: { title: 'Fiches pour apprendre l\'heure à imprimer (horloge, A4) | Kids Learning Hub',
          desc: 'Fiches d\'horloge gratuites à imprimer : heures pile, et demie, et quart puis pas de cinq minutes, une nouvelle feuille A4 à chaque clic — et dans quel ordre.' },
    es: { title: 'Fichas para aprender la hora para imprimir (reloj, A4) | Kids Learning Hub',
          desc: 'Fichas de reloj gratis para imprimir: en punto, y media, y cuarto y pasos de cinco minutos, una hoja A4 nueva con cada clic — y en qué orden enseñarlas.' },
    ar: { title: 'أوراق عمل تعلّم الساعة للطباعة (A4) | Kids Learning Hub',
          desc: 'أوراق ساعة مجانية للطباعة: الساعة التامّة والنصف والربع، وورقة A4 جديدة مع كل نقرة - وبأي ترتيب تُعلّم.' },
  }, emoji: '🕐', ages: '5–9',
  lede: {
    en: 'An analogue clock asks a child to read two hands that move at different speeds, on a dial that counts in fives but is labelled in ones. Almost every difficulty with telling time comes from that mismatch — which is why hours are usually easy and "twenty past" is not.',
    fr: "Une horloge à aiguilles demande à l'enfant de lire deux aiguilles qui avancent à des vitesses différentes, sur un cadran qui compte de cinq en cinq mais dont les nombres vont de un en un. Presque toute la difficulté vient de ce décalage — d'où des heures faciles et un « et vingt » qui ne l'est pas.",
    es: 'Un reloj de agujas pide leer dos manecillas que se mueven a velocidades distintas, sobre una esfera que cuenta de cinco en cinco pero está rotulada de uno en uno. Casi toda la dificultad viene de ese desajuste: por eso las horas en punto son fáciles y «y veinte» no lo es.',
    ar: 'الساعة العقربية تطلب من الطفل قراءة عقربين يتحرّكان بسرعتين مختلفتين، على قرص يعدّ بالخمسات لكنه مرقّم بالآحاد. ومن هذا التعارض تأتي أغلب صعوبات قراءة الوقت — ولذلك تسهل الساعات التامّة ولا يسهل «والثلث».',
  },
  how: {
    en: ['Do the hour hand alone first, and stay there until it is easy. One hand is one problem.',
         'Practise counting in fives before touching minutes — it is the same skill the dial demands.',
         'Order the stages: o\'clock, half past, quarter past and to, then five-minute steps.',
         'Ask for the time on a real clock during the day. A wall clock at snack time teaches more than a page of drills.'],
    fr: ["Travaillez d'abord la petite aiguille seule, et restez-y jusqu'à ce que ce soit facile. Une aiguille, un problème.",
         "Entraînez le comptage de cinq en cinq avant d'aborder les minutes : c'est exactement ce que demande le cadran.",
         "Respectez l'ordre : heures pile, et demie, et quart / moins le quart, puis les pas de cinq minutes.",
         "Demandez l'heure sur une vraie horloge dans la journée. Une pendule au goûter enseigne plus qu'une page d'exercices."],
    es: ['Trabaja primero solo la manecilla de la hora, y quédate ahí hasta que resulte fácil. Una aguja, un problema.',
         'Practica contar de cinco en cinco antes de tocar los minutos: es justo lo que exige la esfera.',
         'Respeta el orden: en punto, y media, y cuarto / menos cuarto, y luego pasos de cinco minutos.',
         'Pregunta la hora en un reloj real durante el día. Un reloj de pared a la hora de la merienda enseña más que una hoja de ejercicios.'],
    ar: ['ابدأ بعقرب الساعات وحده، وابقَ عليه حتى يسهل. عقرب واحد يعني مشكلة واحدة.',
         'تدرّب على العدّ بالخمسات قبل الاقتراب من الدقائق؛ فهي المهارة نفسها التي يطلبها القرص.',
         'رتّب المراحل: الساعة التامّة، ثم النصف، ثم الربع وإلا ربع، ثم خطوات الخمس دقائق.',
         'اسأل عن الوقت على ساعة حقيقية خلال اليوم. ساعة الحائط وقت الوجبة تعلّم أكثر من صفحة تمارين.'],
  },
  faq: {
    en: [['At what age can a child tell the time?', 'Whole hours around 5 or 6, half and quarter hours around 6 or 7, and minute precision usually between 7 and 9. Digital time is often read earlier, but it does not replace understanding the dial.'],
         ['Analogue or digital first?', 'Analogue. A dial shows time as a quantity you can see passing, which is what makes durations meaningful. Digital reading follows easily afterwards; the reverse is much harder.'],
         ['Why does my child confuse the two hands?', 'Because they look similar and move at very different speeds. Cover the minute hand and work only on hours for a while — most of the confusion disappears once each hand is learned separately.']],
    fr: [["À quel âge un enfant sait-il lire l'heure ?", "Les heures pile vers 5–6 ans, les demies et les quarts vers 6–7 ans, et les minutes précises généralement entre 7 et 9 ans. L'heure numérique se lit souvent plus tôt, mais ne remplace pas la compréhension du cadran."],
         ['Analogique ou numérique en premier ?', "Analogique. Le cadran montre le temps comme une quantité qui s'écoule, ce qui donne du sens aux durées. Le numérique s'acquiert facilement ensuite ; l'inverse est bien plus difficile."],
         ['Pourquoi mon enfant confond-il les deux aiguilles ?', "Parce qu'elles se ressemblent et avancent à des vitesses très différentes. Cachez la grande aiguille et travaillez les heures seules un moment : l'essentiel de la confusion disparaît."]],
    es: [['¿A qué edad se aprende a leer la hora?', 'Las horas en punto hacia los 5 o 6, las medias y los cuartos hacia los 6 o 7, y los minutos exactos entre los 7 y los 9. La hora digital se lee antes, pero no sustituye a entender la esfera.'],
         ['¿Analógico o digital primero?', 'Analógico. La esfera muestra el tiempo como una cantidad que se ve pasar, y eso da sentido a las duraciones. Lo digital se adquiere fácil después; al revés es mucho más difícil.'],
         ['¿Por qué confunde las dos manecillas?', 'Porque se parecen y se mueven a velocidades muy distintas. Tapa el minutero y trabaja solo las horas un tiempo: casi toda la confusión desaparece.']],
    ar: [['في أي عمر يقرأ الطفل الوقت؟', 'الساعات التامّة نحو 5 أو 6، والنصف والربع نحو 6 أو 7، ودقّة الدقائق عادة بين 7 و9. وتُقرأ الساعة الرقمية أبكر غالبًا، لكنها لا تغني عن فهم القرص.'],
         ['العقربية أم الرقمية أولًا؟', 'العقربية. فالقرص يُظهر الوقت مقدارًا يُرى وهو يمرّ، وهذا ما يمنح المدد معناها. أما الرقمية فتأتي بسهولة بعدها، والعكس أصعب بكثير.'],
         ['لماذا يخلط طفلي بين العقربين؟', 'لأنهما متشابهان ويتحرّكان بسرعتين مختلفتين جدًا. غطِّ عقرب الدقائق واعمل على الساعات وحدها مدّة، فيزول أغلب الالتباس.']],
  },
},

];
